## Load required packages

In [1]:
#Import required packages

import time
import os
import pandas as pd
import nltk
from nltk.tokenize import TweetTokenizer
from nltk.tokenize import sent_tokenize, word_tokenize
from nltk.stem.snowball import SnowballStemmer
from langdetect import detect
import langdetect
import re
import emoji
import string
import numpy as np

In [2]:
#Get current working directory
cwd = os.getcwd()
cwd

'/Users/Marcel/Desktop/Master Digital Driven Business/Master Project/Data Pre-Processing'

## Load Data

In [4]:
#Load data
Cdata1 = pd.read_csv(os.getcwd() + '/Coosto Manual/Coosto_berichten.csv', 
                     delimiter = ';')
Cdata2 = pd.read_csv(os.getcwd() + '/Coosto Manual/Coosto_berichten (1).csv', 
                     delimiter = ';')
Cdata3 = pd.read_csv(os.getcwd() + '/Coosto Manual/Coosto_berichten (2).csv', 
                     delimiter = ';')
Cdata4 = pd.read_csv(os.getcwd() + '/Coosto Manual/Coosto_berichten (3).csv', 
                     delimiter = ';')
Cdata5 = pd.read_csv(os.getcwd() + '/Coosto Manual/Coosto_berichten (4).csv', 
                     delimiter = ';')
Cdata6 = pd.read_csv(os.getcwd() + '/Coosto Manual/Coosto_berichten (5).csv', 
                     delimiter = ';')
Cdata7 = pd.read_csv(os.getcwd() + '/Coosto Manual/Coosto_berichten (6).csv', 
                     delimiter = ';')
Cdata8 = pd.read_csv(os.getcwd() + '/Coosto Manual/Coosto_berichten (7).csv', 
                     delimiter = ';')
Cdata9 = pd.read_csv(os.getcwd() + '/Coosto Manual/Coosto_berichten (8).csv', 
                     delimiter = ';')
Cdata10 = pd.read_csv(os.getcwd() + '/Coosto Manual/Coosto_berichten (9).csv', 
                     delimiter = ';')
Cdata11 = pd.read_csv(os.getcwd() + '/Coosto Manual/Coosto_berichten (10).csv', 
                     delimiter = ';')
Cdata12 = pd.read_csv(os.getcwd() + '/Coosto Manual/Coosto_berichten (11).csv', 
                     delimiter = ';')
Cdata13 = pd.read_csv(os.getcwd() + '/Coosto Manual/Coosto_berichten (12).csv', 
                     delimiter = ';')
Cdata14 = pd.read_csv(os.getcwd() + '/Coosto Manual/Coosto_berichten (13).csv', 
                     delimiter = ';')
Cdata15 = pd.read_csv(os.getcwd() + '/Coosto Manual/Coosto_berichten (14).csv', 
                     delimiter = ';')
Cdata16 = pd.read_csv(os.getcwd() + '/Coosto Manual/Coosto_berichten (15).csv', 
                     delimiter = ';')
Cdata17 = pd.read_csv(os.getcwd() + '/Coosto Manual/Coosto_berichten (16).csv', 
                     delimiter = ';')
Cdata18 = pd.read_csv(os.getcwd() + '/Coosto Manual/Coosto_berichten (17).csv', 
                     delimiter = ';')
Cdata19 = pd.read_csv(os.getcwd() + '/Coosto Manual/Coosto_berichten (18).csv', 
                     delimiter = ';')
Cdata20 = pd.read_csv(os.getcwd() + '/Coosto Manual/Coosto_berichten (19).csv', 
                     delimiter = ';')
Cdata21 = pd.read_csv(os.getcwd() + '/Coosto Manual/Coosto_berichten (20).csv', 
                     delimiter = ';')
Cdata22 = pd.read_csv(os.getcwd() + '/Coosto Manual/Coosto_berichten (21).csv', 
                     delimiter = ';')

In [5]:
#Clean SearchQuery

#Search Query is limited to a number of characters when manually collecting the data via Coosto. If this is the case through their API,
#is unsure. The right query is required to match the search query to the organizations.

Cdata1['zoekopdracht'] = '"Aalberts N.V." OR "AALB"'
Cdata2['zoekopdracht'] = '"ABN AMRO Group" OR "ABN" OR "ABN AMRO"'
Cdata3['zoekopdracht'] = '"Accell Group" OR "ACCEL"'
Cdata4['zoekopdracht'] = '"Accsys Technologies" OR "AXS" OR "Accsys"'
Cdata5['zoekopdracht'] = '"Adyen" OR "ADYEN"'
Cdata6['zoekopdracht'] = '"AEGON" OR "AGN"'
Cdata7['zoekopdracht'] = '"Koninklijke Ahold" OR "Ahold" OR "AD" OR "Ahold Delhaize"'
Cdata8['zoekopdracht'] = '"shell"'
Cdata9['zoekopdracht'] = '"Air France-KLM" OR "Air France" OR "KLM"'
Cdata10['zoekopdracht'] = '"AkzoNobel" OR "AKZA"'
Cdata11['zoekopdracht'] = '"Alfen" OR "ALFEN"'
Cdata12['zoekopdracht'] = '"Altice Europe" OR "ATC" OR "Altice"'
Cdata13['zoekopdracht'] = '"Coca-Cola European Partners" OR "Coca-Cola" OR "Coca Cola" OR "CCE"'
Cdata14['zoekopdracht'] = '"Greenchoice"'
Cdata15['zoekopdracht'] = '"Vattenfall" OR "NUON"'
Cdata16['zoekopdracht'] = '"Vandebron"'
Cdata17['zoekopdracht'] = '"Eneco"'
Cdata18['zoekopdracht'] = '"Essent"'
Cdata19['zoekopdracht'] = '"ENGIE"'
Cdata20['zoekopdracht'] = '"Nederlandse Energie Maatschappij"'
Cdata21['zoekopdracht'] = '"Oxxio"'
Cdata22['zoekopdracht'] = '"Alliander" OR "Liander" OR "Qirion" OR "Kenter"'

In [6]:
pd.set_option('display.max_colwidth', None) #Show ful message

In [7]:
#Concat data
Data = pd.concat([Cdata1, Cdata2, Cdata3, Cdata4, Cdata5, Cdata6, Cdata7, Cdata8, Cdata9, Cdata10, Cdata11, Cdata12,
                  Cdata13, Cdata14, Cdata15, Cdata16, Cdata17, Cdata18, Cdata19, Cdata20, Cdata21, Cdata22])

#Delete unnecessary columns
del Data['sentiment']
del Data['url']
del Data['type']
del Data['views']
del Data['discussielengte']
del Data['auteur']
del Data['volgers']
del Data['invloed']
del Data['GPS breedtegraad']
del Data['GPS lengtegraad']
#del Data['type bron']
del Data['titel']

#See full message
pd.set_option('display.max_colwidth', None) #Show ful message

Data

,zoekopdracht,datum,bericht tekst,type bron
0,"""Aalberts N.V."" OR ""AALB""",2021-04-12 18:18,Aero Logic | D-[AALB] | Boeing 777-FZN | Clitheroe 12/04/2021 #aerologic #daalb #boeing #boeing777 #boeing777f #cargo #avgeek #aviation #planes #planespotting #planespotter #aviationphotography #airplan #aircraft #planespotter #fly #photography #spotting #highflyers #ott https://t.co/4uYPiwTjAw,twitter
1,"""Aalberts N.V."" OR ""AALB""",2021-03-18 11:53,$[AALB] #AALBERTS @aalbertsindustr - Dagelijks: AALBERTS NV maakt een erg sterke bullish trend door. Traders kunnen overwegen alleen longposities te handelen (op moment van aankoop) zolang de koers... https://t.co/hOiR5KPSeX,twitter
2,"""Aalberts N.V."" OR ""AALB""",2021-03-18 11:53,$[AALB] #AALBERTS - Dagelijks: AALBERTS NV maakt een erg sterke bullish trend door. Traders kunnen overwegen alleen longposities te handelen (op moment van aankoop) zolang de koers... https://t.co/dZWInNPIYj,twitter
3,"""Aalberts N.V."" OR ""AALB""",2021-02-16 12:41,Nederlandse scale-up Nearfield vult het metrologie-gat in de mondiale chipindustrie #3Dstructuren Aalberts advanced mechatronics [Aalberts N.V]. #advancedmotioncontrol #AMAT Applied Materials ASML #BenjaminBunday #chipindustrie #d…https://t.co/dTyXJs2KcP https://t.co/3R88TCMjts,twitter
4,"""Aalberts N.V."" OR ""AALB""",2020-11-05 14:53,"Zojuist de [AALB] dec20 30 call (optietip 176) verkocht voor €3,25. Gekocht voor €1,10. Had achteraf gezien beter gekund, maar je kunt toch niet echt ontevreden zijn met 195% winst. https://t.co/OsAvGABjst",twitter
...,...,...,...,...
9995,"""Alliander"" OR ""Liander"" OR ""Qirion"" OR ""Kenter""",2019-07-13 12:10,"https://t.co/NYnpVpVauf | #Vacature #Beleidsadviseur #Laagspanning | [Liander] | Landelijk | Ben jij de nauwkeurige, gedreven Beleidsadviseur die we zoeken? Kom ons team versterken! #Solliciteer #JobsinEnergy https://t.co/mHSftqxbtG",twitter
9996,"""Alliander"" OR ""Liander"" OR ""Qirion"" OR ""Kenter""",2019-07-13 11:30,https://t.co/mV9RK1qWGD | #Vacature #HSE #Business #Partner | [Liander] | Amsterdam | Ben jij die HSE professional met ervaring binnen een projectorganisatie? #Solliciteer #JobsinEnergy https://t.co/vbTEri0EAS,twitter
9997,"""Alliander"" OR ""Liander"" OR ""Qirion"" OR ""Kenter""",2019-07-13 11:00,https://t.co/BTP2UnDA0f | #Consultant – rol #Scrummaster | [Liander] | Duiven | Ben jij de pragmatische Scrummaster die we zoeken? Kom ons team versterken! | #JobsinEnergy | #Solliciteer https://t.co/1wfjeGqaTD,twitter
9998,"""Alliander"" OR ""Liander"" OR ""Qirion"" OR ""Kenter""",2019-07-13 10:22,Onderhoudsmonteur machines / installaties – Leeuwarden – [Alliander] – Leeuwarden https://t.co/210Z26FpnL,twitter
9999,"""Alliander"" OR ""Liander"" OR ""Qirion"" OR ""Kenter""",2019-07-13 10:04,#Stroomstoring #Hoogkarspel #Wervershoof (postcode 1616 en 1639) is opgelost. Er is op dit moment nog geen oorzaak bekend. Excuses voor het ongemak. [#Liander],twitter

In [6]:
#Check for NAN's and empty fields
Data.dropna(inplace=True)
NA=pd.concat([Data.isnull().sum(),Data.eq('').sum()],keys=['Nulls','Empty'],axis=1)
NA

               Nulls  Empty
zoekopdracht       0      0
datum              0      0
bericht tekst      0      0
type bron          0      0

In [104]:
#Detect language

def det(x):
    try:
        lang = detect(x)
    except:
        lang = 'Other'
    return lang

Data['Lang'] = Data['bericht tekst'].apply(det)
#Data

In [7]:
#Remove rows with less than 5 characters

#Create new dataframe with number of chars in the message
Data['Number of Chars'] = Data['bericht tekst'].str.len()

#Subset where number of chars is bigger than 10
Data2 = Data[Data['Number of Chars'] > 10]  

#Delete column Number of Chars
del Data2['Number of Chars']


Data2

,zoekopdracht,datum,bericht tekst,type bron
0,"""Aalberts N.V."" OR ""AALB""",2021-04-12 18:18,Aero Logic | D-[AALB] | Boeing 777-FZN | Clitheroe 12/04/2021 #aerologic #daalb #boeing #boeing777 #boeing777f #cargo #avgeek #aviation #planes #planespotting #planespotter #aviationphotography #airplan #aircraft #planespotter #fly #photography #spotting #highflyers #ott https://t.co/4uYPiwTjAw,twitter
1,"""Aalberts N.V."" OR ""AALB""",2021-03-18 11:53,$[AALB] #AALBERTS @aalbertsindustr - Dagelijks: AALBERTS NV maakt een erg sterke bullish trend door. Traders kunnen overwegen alleen longposities te handelen (op moment van aankoop) zolang de koers... https://t.co/hOiR5KPSeX,twitter
2,"""Aalberts N.V."" OR ""AALB""",2021-03-18 11:53,$[AALB] #AALBERTS - Dagelijks: AALBERTS NV maakt een erg sterke bullish trend door. Traders kunnen overwegen alleen longposities te handelen (op moment van aankoop) zolang de koers... https://t.co/dZWInNPIYj,twitter
3,"""Aalberts N.V."" OR ""AALB""",2021-02-16 12:41,Nederlandse scale-up Nearfield vult het metrologie-gat in de mondiale chipindustrie #3Dstructuren Aalberts advanced mechatronics [Aalberts N.V]. #advancedmotioncontrol #AMAT Applied Materials ASML #BenjaminBunday #chipindustrie #d…https://t.co/dTyXJs2KcP https://t.co/3R88TCMjts,twitter
4,"""Aalberts N.V."" OR ""AALB""",2020-11-05 14:53,"Zojuist de [AALB] dec20 30 call (optietip 176) verkocht voor €3,25. Gekocht voor €1,10. Had achteraf gezien beter gekund, maar je kunt toch niet echt ontevreden zijn met 195% winst. https://t.co/OsAvGABjst",twitter
...,...,...,...,...
9995,"""Alliander"" OR ""Liander"" OR ""Qirion"" OR ""Kenter""",2019-07-13 12:10,"https://t.co/NYnpVpVauf | #Vacature #Beleidsadviseur #Laagspanning | [Liander] | Landelijk | Ben jij de nauwkeurige, gedreven Beleidsadviseur die we zoeken? Kom ons team versterken! #Solliciteer #JobsinEnergy https://t.co/mHSftqxbtG",twitter
9996,"""Alliander"" OR ""Liander"" OR ""Qirion"" OR ""Kenter""",2019-07-13 11:30,https://t.co/mV9RK1qWGD | #Vacature #HSE #Business #Partner | [Liander] | Amsterdam | Ben jij die HSE professional met ervaring binnen een projectorganisatie? #Solliciteer #JobsinEnergy https://t.co/vbTEri0EAS,twitter
9997,"""Alliander"" OR ""Liander"" OR ""Qirion"" OR ""Kenter""",2019-07-13 11:00,https://t.co/BTP2UnDA0f | #Consultant – rol #Scrummaster | [Liander] | Duiven | Ben jij de pragmatische Scrummaster die we zoeken? Kom ons team versterken! | #JobsinEnergy | #Solliciteer https://t.co/1wfjeGqaTD,twitter
9998,"""Alliander"" OR ""Liander"" OR ""Qirion"" OR ""Kenter""",2019-07-13 10:22,Onderhoudsmonteur machines / installaties – Leeuwarden – [Alliander] – Leeuwarden https://t.co/210Z26FpnL,twitter
9999,"""Alliander"" OR ""Liander"" OR ""Qirion"" OR ""Kenter""",2019-07-13 10:04,#Stroomstoring #Hoogkarspel #Wervershoof (postcode 1616 en 1639) is opgelost. Er is op dit moment nog geen oorzaak bekend. Excuses voor het ongemak. [#Liander],twitter

## Select only Tweets in Dutch

In [ ]:
DataNL = Data2[Data2['Lang'] == 'nl']
#DataNL = Data2.loc[Data['Lang'] == 'nl']
DataNL

In [24]:
#Create subset to minimize RAM usage
Data3 = Data2.sample(frac=1).reset_index(drop=True).head(40000)

In [13]:
Data3

,zoekopdracht,datum,bericht tekst,type bron,Number of Chars
0,"""Vattenfall"" OR ""NUON"" (src:twit...",2019-05-06 05:31,Er is op 06-05-2019 een nieuwe beoordeling geplaatst voor [NUON]! https://t.co/MRvtZvstcW,twitter,89
1,"""Nederlandse Energie Maatschappi...",2018-01-03 15:40,Investeerder Waterland koopt de [Nederlandse Energie Maatschappij] https://t.co/OOaSDiL2X0… https://t.co/6Mk4nvUPfE #BusinessInsider,twitter,132
2,"""Alliander"" OR ""Liander"" OR ""Qir...",2020-11-02 08:14,Volgens gebruikersmeldingen zijn er sinds 08:14 problemen op [Liander]. https://t.co/PxtItyGdln Retweet als je ook problemen ondervindt #lianderstoring,twitter,151
3,"""Vandebron"" (src:twitter) extra:...",2016-10-20 17:15,"Yes, we hebben een 9,6! Voor de tweede keer op rij staat [Vandebron] in de top van de groenste energieleveranciers,... https://t.co/B701DnXh4c",twitter,142
4,"""Greenchoice"" (src:twitter) extr...",2020-01-21 13:14,Gemeente Utrecht Kiest Voor 100% Groene Duurzame Energie by [Greenchoice] https://t.co/zJbNxp8Iwe,twitter,98
...,...,...,...,...,...
39995,"""Koninklijke Ahold"" OR ""Ahold"" O...",2020-06-26 20:40,"Parmalat, Enron, [Ahold]: de lijst met grote boekhoudfraudes is lang. Wirecard mag zich nu ook bij dat rijtje voegen. Waarom greep accountant EY niet in? Fraudesignalen waren er immers al jaren. @jorgleijten https://t.co/GRhlb6rnMn",twitter,231
39996,"""Koninklijke Ahold"" OR ""Ahold"" O...",2019-04-23 16:02,[Ahold Delhaize] drukt AEX in het rood: AMSTERDAM (AFN) - De AEX-index in Amsterdam stond dinsdagmiddag in de min. Met name het verlies van zwaargewicht [Ahold Delhaize] liet zich voelen. Het supermarkt stelde zijn financiële doelen neerwaarts bij en kreeg… https://t.co/GOnrjEf7mV,twitter,281
39997,"""Alliander"" OR ""Liander"" OR ""Qir...",2020-04-15 07:19,Solar Magazine - Netbeheerder [Liander] verwelkomt in eerste kwartaal 142 megawattpiek aan zonnepanelen https://t.co/RaPIufmjmX,twitter,127
39998,"""Altice Europe"" OR ""ATC"" OR ""Alt...",2020-06-23 14:14,[Altice Europe] verkoopt restbelang in [Altice] USA https://t.co/mYXdYEpcwP,twitter,76
39999,"""Altice Europe"" OR ""ATC"" OR ""Alt...",2018-08-27 19:20,Check out our website to learn more about ATVehicle™ and our latest project with @ANSFinland https://t.co/CYomgrIw90 [#ATC] #ATCSimulation https://t.co/PATMine9Zm,twitter,162

## Clean data

In [220]:
#Data2 = Data.head(1500)

def clean_text(text):
    #Clean text
    text = re.sub(r"(?:\@|http?\://|https?\://|www)\S+", "", text) #Remove http links
    text = re.sub("[^a-zA-Z]", " ", text)# Search for all non-letters # Replace all non-letters with spaces
    text = text.lower() #Lower text
    text = re.sub('\[.*?\]', '', text)
    #text = re.sub(r"(?:\@|http?\://|https?\://|www)\S+", "", text) #Remove http links
    text = re.sub('[%s]' % re.escape(string.punctuation), '', text)
    text = re.sub('\w*\d\w*', '', text) #Remove numbers and text with numbers   
    text = ''.join(c for c in text if c not in emoji.UNICODE_EMOJI) #Remove Emojis
    text = re.sub('\n', '', text) #Remove \n
    text = re.sub('€', '', text) #Remove €
    
    # tokenize text and remove puncutation
    text = [word.strip(string.punctuation) for word in text.split(" ")]

    #Remove stopwords
    #Dutch stop words
    stop = nltk.corpus.stopwords.words('dutch')
    text = [word for word in text if word not in stop]    
    
    # remove empty tokens and tokens with 1 
    text = [t for t in text if len(t) > 1]    
    
    return text

#Clean text data
#DataNL['Text Clean'] = DataNL['bericht tekst'].apply(lambda x: clean_text(x))

#Stem cleaned data
#dutchStemmer=SnowballStemmer("dutch")
#DataNL['Stemmed Clean'] = DataNL['Text Clean'].apply(lambda x: [dutchStemmer.stem(y) for y in x]) # Stem every word.

#Note: Stemming makes words incorrect

In [31]:
DataNL

,zoekopdracht,datum,bericht tekst,type bron,Lang,Text Clean,Stemmed Clean,Subjectivity,Sentiment,Subjectivity
0,"""Aalberts N.V."" OR ""AALB""",2021-03-18 11:53,$[AALB] #AALBERTS @aalbertsindustr - Dagelijks: AALBERTS NV maakt een erg sterke bullish trend door. Traders kunnen overwegen alleen longposities te handelen (op moment van aankoop) zolang de koers... https://t.co/hOiR5KPSeX,twitter,nl,"[aalb, aalberts, dagelijks, aalberts, nv, maakt, erg, sterke, bullish, trend, traders, overwegen, alleen, longposities, handelen, moment, aankoop, zolang, koers]","['aalb', 'aalbert', 'dagelijk', 'aalbert', 'nv', 'maakt', 'erg', 'sterk', 'bullish', 'trend', 'trader', 'overweg', 'allen', 'longposities', 'handel', 'moment', 'aankop', 'zolang', 'koer']",0.650,0.388333,0.650
1,"""Aalberts N.V."" OR ""AALB""",2021-03-18 11:53,$[AALB] #AALBERTS - Dagelijks: AALBERTS NV maakt een erg sterke bullish trend door. Traders kunnen overwegen alleen longposities te handelen (op moment van aankoop) zolang de koers... https://t.co/dZWInNPIYj,twitter,nl,"[aalb, aalberts, dagelijks, aalberts, nv, maakt, erg, sterke, bullish, trend, traders, overwegen, alleen, longposities, handelen, moment, aankoop, zolang, koers]","['aalb', 'aalbert', 'dagelijk', 'aalbert', 'nv', 'maakt', 'erg', 'sterk', 'bullish', 'trend', 'trader', 'overweg', 'allen', 'longposities', 'handel', 'moment', 'aankop', 'zolang', 'koer']",0.650,0.388333,0.650
2,"""Aalberts N.V."" OR ""AALB""",2020-11-05 14:53,"Zojuist de [AALB] dec20 30 call (optietip 176) verkocht voor €3,25. Gekocht voor €1,10. Had achteraf gezien beter gekund, maar je kunt toch niet echt ontevreden zijn met 195% winst. https://t.co/OsAvGABjst",twitter,nl,"[zojuist, aalb, dec, call, optietip, verkocht, gekocht, achteraf, gezien, beter, gekund, kunt, echt, ontevreden, winst]","['zojuist', 'aalb', 'dec', 'call', 'optietip', 'verkocht', 'gekocht', 'achteraf', 'gezien', 'beter', 'gekund', 'kunt', 'echt', 'ontevred', 'winst']",0.625,0.125000,0.625
3,"""Aalberts N.V."" OR ""AALB""",2020-08-11 11:41,#Aalberts [#AALB] laat een mooie uitbraak zien boven de 200MA curve. Vanaf 20-07-20 in portfolio. Target €35.00 https://t.co/FxvCgNF88F,twitter,nl,"[aalberts, aalb, laat, mooie, uitbraak, zien, boven, ma, curve, vanaf, portfolio, target]","['aalbert', 'aalb', 'lat', 'mooi', 'uitbrak', 'zien', 'bov', 'ma', 'curv', 'vanaf', 'portfolio', 'target']",0.800,0.200000,0.800
4,"""Aalberts N.V."" OR ""AALB""",2020-04-01 16:43,Koenie's Corona Crash bodem kooplijstje: 1-ABN 2-AGN 3-[AALB] 4-ASML 5-ABI 6-MT 7-DSM 8-GLPG 9-HEI 10-ING 11-LIGHT 12-PHI 13-RDSA 14-UNIA 15-DEL2 Not Yet...W8 4 iT!,twitter,nl,"[koenie, corona, crash, bodem, kooplijstje, abn, agn, aalb, asml, abi, mt, dsm, glpg, hei, ing, light, phi, rdsa, unia, del, not, yet, it]","['koenie', 'corona', 'crash', 'bodem', 'kooplijstj', 'abn', 'agn', 'aalb', 'asml', 'abi', 'mt', 'dsm', 'glpg', 'hei', 'ing', 'light', 'phi', 'rdsa', 'unia', 'del', 'not', 'yet', 'it']",0.000,0.000000,0.000
...,...,...,...,...,...,...,...,...,...,...
128995,"""Alliander"" OR ""Liander"" OR ""Qirion"" OR ""Kenter""",2019-07-13 12:10,"https://t.co/NYnpVpVauf | #Vacature #Beleidsadviseur #Laagspanning | [Liander] | Landelijk | Ben jij de nauwkeurige, gedreven Beleidsadviseur die we zoeken? Kom ons team versterken! #Solliciteer #JobsinEnergy https://t.co/mHSftqxbtG",twitter,nl,"[vacature, beleidsadviseur, laagspanning, liander, landelijk, jij, nauwkeurige, gedreven, beleidsadviseur, we, zoeken, kom, team, versterken, solliciteer, jobsinenergy]","['vacatur', 'beleidsadviseur', 'laagspann', 'liander', 'landelijk', 'jij', 'nauwkeur', 'gedrev', 'beleidsadviseur', 'we', 'zoek', 'kom', 'team', 'versterk', 'solliciter', 'jobsinenergy']",0.550,0.500000,0.550
128996,"""Alliander"" OR ""Liander"" OR ""Qirion"" OR ""Kenter""",2019-07-13 11:30,https://t.co/mV9RK1qWGD | #Vacature #HSE #Business #Partner | [Liander] | Amsterdam | Ben jij die HSE professional met ervaring binnen een projectorganisatie? #Solliciteer #JobsinEnergy https://t.co/vbTEri0EAS,twitter,nl,"[vacature, hse, business, partner, liander, amsterdam, jij, hse, professional, ervaring, binnen, projectorganisatie, solliciteer, jobsinenergy]","['vacatur', 'hse', 'busines', 'partner', 'liander', 'amsterdam', 'jij', 'hse', 'professional', 'ervar', 'binn', 'projectorganisatie', 'solliciter', 'jobsinenergy']",0.000,0.000000,0.000
128997,"""Alliander"" OR ""Liander"" OR ""Qirion"" OR ""Kenter""",2019-07-13 11:00,https://t.co/BTP2UnDA0f | #Consultant – rol #Scrummaster | [Liander] | Duiven | Ben jij de pragmatische Scrummaster die we zoeken? Kom ons team versterken! | #JobsinEnergy | #Solliciteer https://t.co/1wfjeGqaTD,twitter,nl,"[consultant, rol, scrummaster, liander, duiven, jij, pragmatische, scrummaster, we, zoeken, kom, team, versterken, jobsinenergy, solliciteer]","['consultant', 'rol', 'scrummaster', 'liander', 'duiv', 'jij', 'pragmatisch', 'scrummaster', 'we', 'zoek', 'kom', 'team', 'versterk', 'jobsinenergy', 'solliciter']",0.000,0.000000,0.000
128998,"""Alliander"" OR ""Liander"" OR ""Qirion"" OR ""Kenter""",2019-07-13 10:22,Onderhoudsmonteur machines / installaties – Leeuwarden – [Alliander] – Leeuwarden https://t.co/210Z26FpnL,twitter,nl,"[onderhoudsmonteur, machines, installaties, leeuwarden, alliander, leeuwarden]","['onderhoudsmonteur', 'machines', 'installaties', 'leeuward', 'alliander', 'leeuward']",0.000,0.000000,0.000
128999,"""Alliander"" OR ""Liander"" OR ""Qirion"" OR ""Kenter""",2019-07-13 10:04,#Stroomstoring #Hoogkarspel #Wervershoof (postcode 1616 en 1639) is opgelost. Er is op dit moment nog geen oorzaak bekend. Excuses voor het ongemak. [#Liander],twitter,nl,"[stroomstoring, hoogkarspel, wervershoof, postcode, opgelost, moment, oorzaak, bekend, excuses, ongemak, liander]","['stroomstor', 'hoogkarspel', 'wervershof', 'postcod', 'opgelost', 'moment', 'oorzak', 'bekend', 'excuses', 'ongemak', 'liander']",0.800,0.350000,0.800

In [111]:
#Save DF
#DataNL.to_csv('Coosto_Clean_NL.csv')

## Sentiment analysis

#Calculate the sentiment over a Tweet whether it's positive or negative

In [8]:
#Read clean csv if necessary

DataNL = pd.read_csv('Coosto_Clean_NL.csv')
del DataNL['Unnamed: 0']
del DataNL['type bron']
del DataNL['Stemmed Clean']
del DataNL['Subjectivity']
del DataNL['Lang']
DataNL
#DataNL

,zoekopdracht,datum,bericht tekst,Text Clean,Sentiment
0,"""Aalberts N.V."" OR ""AALB""",2021-03-18 11:53,$[AALB] #AALBERTS @aalbertsindustr - Dagelijks: AALBERTS NV maakt een erg sterke bullish trend door. Traders kunnen overwegen alleen longposities te handelen (op moment van aankoop) zolang de koers... https://t.co/hOiR5KPSeX,"['aalb', 'aalberts', 'dagelijks', 'aalberts', 'nv', 'maakt', 'erg', 'sterke', 'bullish', 'trend', 'traders', 'overwegen', 'alleen', 'longposities', 'handelen', 'moment', 'aankoop', 'zolang', 'koers']",0.388333
1,"""Aalberts N.V."" OR ""AALB""",2021-03-18 11:53,$[AALB] #AALBERTS - Dagelijks: AALBERTS NV maakt een erg sterke bullish trend door. Traders kunnen overwegen alleen longposities te handelen (op moment van aankoop) zolang de koers... https://t.co/dZWInNPIYj,"['aalb', 'aalberts', 'dagelijks', 'aalberts', 'nv', 'maakt', 'erg', 'sterke', 'bullish', 'trend', 'traders', 'overwegen', 'alleen', 'longposities', 'handelen', 'moment', 'aankoop', 'zolang', 'koers']",0.388333
2,"""Aalberts N.V."" OR ""AALB""",2020-11-05 14:53,"Zojuist de [AALB] dec20 30 call (optietip 176) verkocht voor €3,25. Gekocht voor €1,10. Had achteraf gezien beter gekund, maar je kunt toch niet echt ontevreden zijn met 195% winst. https://t.co/OsAvGABjst","['zojuist', 'aalb', 'dec', 'call', 'optietip', 'verkocht', 'gekocht', 'achteraf', 'gezien', 'beter', 'gekund', 'kunt', 'echt', 'ontevreden', 'winst']",0.125000
3,"""Aalberts N.V."" OR ""AALB""",2020-08-11 11:41,#Aalberts [#AALB] laat een mooie uitbraak zien boven de 200MA curve. Vanaf 20-07-20 in portfolio. Target €35.00 https://t.co/FxvCgNF88F,"['aalberts', 'aalb', 'laat', 'mooie', 'uitbraak', 'zien', 'boven', 'ma', 'curve', 'vanaf', 'portfolio', 'target']",0.200000
4,"""Aalberts N.V."" OR ""AALB""",2020-04-01 16:43,Koenie's Corona Crash bodem kooplijstje: 1-ABN 2-AGN 3-[AALB] 4-ASML 5-ABI 6-MT 7-DSM 8-GLPG 9-HEI 10-ING 11-LIGHT 12-PHI 13-RDSA 14-UNIA 15-DEL2 Not Yet...W8 4 iT!,"['koenie', 'corona', 'crash', 'bodem', 'kooplijstje', 'abn', 'agn', 'aalb', 'asml', 'abi', 'mt', 'dsm', 'glpg', 'hei', 'ing', 'light', 'phi', 'rdsa', 'unia', 'del', 'not', 'yet', 'it']",0.000000
...,...,...,...,...,...
128995,"""Alliander"" OR ""Liander"" OR ""Qirion"" OR ""Kenter""",2019-07-13 12:10,"https://t.co/NYnpVpVauf | #Vacature #Beleidsadviseur #Laagspanning | [Liander] | Landelijk | Ben jij de nauwkeurige, gedreven Beleidsadviseur die we zoeken? Kom ons team versterken! #Solliciteer #JobsinEnergy https://t.co/mHSftqxbtG","['vacature', 'beleidsadviseur', 'laagspanning', 'liander', 'landelijk', 'jij', 'nauwkeurige', 'gedreven', 'beleidsadviseur', 'we', 'zoeken', 'kom', 'team', 'versterken', 'solliciteer', 'jobsinenergy']",0.500000
128996,"""Alliander"" OR ""Liander"" OR ""Qirion"" OR ""Kenter""",2019-07-13 11:30,https://t.co/mV9RK1qWGD | #Vacature #HSE #Business #Partner | [Liander] | Amsterdam | Ben jij die HSE professional met ervaring binnen een projectorganisatie? #Solliciteer #JobsinEnergy https://t.co/vbTEri0EAS,"['vacature', 'hse', 'business', 'partner', 'liander', 'amsterdam', 'jij', 'hse', 'professional', 'ervaring', 'binnen', 'projectorganisatie', 'solliciteer', 'jobsinenergy']",0.000000
128997,"""Alliander"" OR ""Liander"" OR ""Qirion"" OR ""Kenter""",2019-07-13 11:00,https://t.co/BTP2UnDA0f | #Consultant – rol #Scrummaster | [Liander] | Duiven | Ben jij de pragmatische Scrummaster die we zoeken? Kom ons team versterken! | #JobsinEnergy | #Solliciteer https://t.co/1wfjeGqaTD,"['consultant', 'rol', 'scrummaster', 'liander', 'duiven', 'jij', 'pragmatische', 'scrummaster', 'we', 'zoeken', 'kom', 'team', 'versterken', 'jobsinenergy', 'solliciteer']",0.000000
128998,"""Alliander"" OR ""Liander"" OR ""Qirion"" OR ""Kenter""",2019-07-13 10:22,Onderhoudsmonteur machines / installaties – Leeuwarden – [Alliander] – Leeuwarden https://t.co/210Z26FpnL,"['onderhoudsmonteur', 'machines', 'installaties', 'leeuwarden', 'alliander', 'leeuwarden']",0.000000
128999,"""Alliander"" OR ""Liander"" OR ""Qirion"" OR ""Kenter""",2019-07-13 10:04,#Stroomstoring #Hoogkarspel #Wervershoof (postcode 1616 en 1639) is opgelost. Er is op dit moment nog geen oorzaak bekend. Excuses voor het ongemak. [#Liander],"['stroomstoring', 'hoogkarspel', 'wervershoof', 'postcode', 'opgelost', 'moment', 'oorzaak', 'bekend', 'excuses', 'ongemak', 'liander']",0.350000

In [68]:
from pattern.nl import sentiment


def senti(text):
    text = sentiment(text)

    #text['Sentiment'] = text['bericht tekst'].apply(sentiment)
    
    return text

DataNL['Sentiment'] = DataNL['bericht tekst'].apply(senti)
DataNL = pd.concat([DataNL.drop(['Sentiment'], axis=1), DataNL['Sentiment'].apply(pd.Series)], axis=1).rename(columns={0:'Sentiment', 1:'Subjectivity'})
DataNL

,zoekopdracht,datum,bericht tekst,type bron,Lang,Text Clean,Stemmed Clean,Sentiment,Subjectivity
0,"""Aalberts N.V."" OR ""AALB""",2021-03-18 11:53,$[AALB] #AALBERTS @aalbertsindustr - Dagelijks: AALBERTS NV maakt een erg sterke bullish trend door. Traders kunnen overwegen alleen longposities te handelen (op moment van aankoop) zolang de koers... https://t.co/hOiR5KPSeX,twitter,nl,"['aalb', 'aalberts', 'dagelijks', 'aalberts', 'nv', 'maakt', 'erg', 'sterke', 'bullish', 'trend', 'traders', 'overwegen', 'alleen', 'longposities', 'handelen', 'moment', 'aankoop', 'zolang', 'koers']","['aalb', 'aalbert', 'dagelijk', 'aalbert', 'nv', 'maakt', 'erg', 'sterk', 'bullish', 'trend', 'trader', 'overweg', 'allen', 'longposities', 'handel', 'moment', 'aankop', 'zolang', 'koer']",0.388333,0.650
1,"""Aalberts N.V."" OR ""AALB""",2021-03-18 11:53,$[AALB] #AALBERTS - Dagelijks: AALBERTS NV maakt een erg sterke bullish trend door. Traders kunnen overwegen alleen longposities te handelen (op moment van aankoop) zolang de koers... https://t.co/dZWInNPIYj,twitter,nl,"['aalb', 'aalberts', 'dagelijks', 'aalberts', 'nv', 'maakt', 'erg', 'sterke', 'bullish', 'trend', 'traders', 'overwegen', 'alleen', 'longposities', 'handelen', 'moment', 'aankoop', 'zolang', 'koers']","['aalb', 'aalbert', 'dagelijk', 'aalbert', 'nv', 'maakt', 'erg', 'sterk', 'bullish', 'trend', 'trader', 'overweg', 'allen', 'longposities', 'handel', 'moment', 'aankop', 'zolang', 'koer']",0.388333,0.650
2,"""Aalberts N.V."" OR ""AALB""",2020-11-05 14:53,"Zojuist de [AALB] dec20 30 call (optietip 176) verkocht voor €3,25. Gekocht voor €1,10. Had achteraf gezien beter gekund, maar je kunt toch niet echt ontevreden zijn met 195% winst. https://t.co/OsAvGABjst",twitter,nl,"['zojuist', 'aalb', 'dec', 'call', 'optietip', 'verkocht', 'gekocht', 'achteraf', 'gezien', 'beter', 'gekund', 'kunt', 'echt', 'ontevreden', 'winst']","['zojuist', 'aalb', 'dec', 'call', 'optietip', 'verkocht', 'gekocht', 'achteraf', 'gezien', 'beter', 'gekund', 'kunt', 'echt', 'ontevred', 'winst']",0.125000,0.625
3,"""Aalberts N.V."" OR ""AALB""",2020-08-11 11:41,#Aalberts [#AALB] laat een mooie uitbraak zien boven de 200MA curve. Vanaf 20-07-20 in portfolio. Target €35.00 https://t.co/FxvCgNF88F,twitter,nl,"['aalberts', 'aalb', 'laat', 'mooie', 'uitbraak', 'zien', 'boven', 'ma', 'curve', 'vanaf', 'portfolio', 'target']","['aalbert', 'aalb', 'lat', 'mooi', 'uitbrak', 'zien', 'bov', 'ma', 'curv', 'vanaf', 'portfolio', 'target']",0.200000,0.800
4,"""Aalberts N.V."" OR ""AALB""",2020-04-01 16:43,Koenie's Corona Crash bodem kooplijstje: 1-ABN 2-AGN 3-[AALB] 4-ASML 5-ABI 6-MT 7-DSM 8-GLPG 9-HEI 10-ING 11-LIGHT 12-PHI 13-RDSA 14-UNIA 15-DEL2 Not Yet...W8 4 iT!,twitter,nl,"['koenie', 'corona', 'crash', 'bodem', 'kooplijstje', 'abn', 'agn', 'aalb', 'asml', 'abi', 'mt', 'dsm', 'glpg', 'hei', 'ing', 'light', 'phi', 'rdsa', 'unia', 'del', 'not', 'yet', 'it']","['koenie', 'corona', 'crash', 'bodem', 'kooplijstj', 'abn', 'agn', 'aalb', 'asml', 'abi', 'mt', 'dsm', 'glpg', 'hei', 'ing', 'light', 'phi', 'rdsa', 'unia', 'del', 'not', 'yet', 'it']",0.000000,0.000
...,...,...,...,...,...,...,...,...,...
128995,"""Alliander"" OR ""Liander"" OR ""Qirion"" OR ""Kenter""",2019-07-13 12:10,"https://t.co/NYnpVpVauf | #Vacature #Beleidsadviseur #Laagspanning | [Liander] | Landelijk | Ben jij de nauwkeurige, gedreven Beleidsadviseur die we zoeken? Kom ons team versterken! #Solliciteer #JobsinEnergy https://t.co/mHSftqxbtG",twitter,nl,"['vacature', 'beleidsadviseur', 'laagspanning', 'liander', 'landelijk', 'jij', 'nauwkeurige', 'gedreven', 'beleidsadviseur', 'we', 'zoeken', 'kom', 'team', 'versterken', 'solliciteer', 'jobsinenergy']","['vacatur', 'beleidsadviseur', 'laagspann', 'liander', 'landelijk', 'jij', 'nauwkeur', 'gedrev', 'beleidsadviseur', 'we', 'zoek', 'kom', 'team', 'versterk', 'solliciter', 'jobsinenergy']",0.500000,0.550
128996,"""Alliander"" OR ""Liander"" OR ""Qirion"" OR ""Kenter""",2019-07-13 11:30,https://t.co/mV9RK1qWGD | #Vacature #HSE #Business #Partner | [Liander] | Amsterdam | Ben jij die HSE professional met ervaring binnen een projectorganisatie? #Solliciteer #JobsinEnergy https://t.co/vbTEri0EAS,twitter,nl,"['vacature', 'hse', 'business', 'partner', 'liander', 'amsterdam', 'jij', 'hse', 'professional', 'ervaring', 'binnen', 'projectorganisatie', 'solliciteer', 'jobsinenergy']","['vacatur', 'hse', 'busines', 'partner', 'liander', 'amsterdam', 'jij', 'hse', 'professional', 'ervar', 'binn', 'projectorganisatie', 'solliciter', 'jobsinenergy']",0.000000,0.000
128997,"""Alliander"" OR ""Liander"" OR ""Qirion"" OR ""Kenter""",2019-07-13 11:00,https://t.co/BTP2UnDA0f | #Consultant – rol #Scrummaster | [Liander] | Duiven | Ben jij de pragmatische Scrummaster die we zoeken? Kom ons team versterken! | #JobsinEnergy | #Solliciteer https://t.co/1wfjeGqaTD,twitter,nl,"['consultant', 'rol', 'scrummaster', 'liander', 'duiven', 'jij', 'pragmatische', 'scrummaster', 'we', 'zoeken', 'kom', 'team', 'versterken', 'jobsinenergy', 'solliciteer']","['consultant', 'rol', 'scrummaster', 'liander', 'duiv', 'jij', 'pragmatisch', 'scrummaster', 'we', 'zoek', 'kom', 'team', 'versterk', 'jobsinenergy', 'solliciter']",0.000000,0.000
128998,"""Alliander"" OR ""Liander"" OR ""Qirion"" OR ""Kenter""",2019-07-13 10:22,Onderhoudsmonteur machines / installaties – Leeuwarden – [Alliander] – Leeuwarden https://t.co/210Z26FpnL,twitter,nl,"['onderhoudsmonteur', 'machines', 'installaties', 'leeuwarden', 'alliander', 'leeuwarden']","['onderhoudsmonteur', 'machines', 'installaties', 'leeuward', 'alliander', 'leeuward']",0.000000,0.000
128999,"""Alliander"" OR ""Liander"" OR ""Qirion"" OR ""Kenter""",2019-07-13 10:04,#Stroomstoring #Hoogkarspel #Wervershoof (postcode 1616 en 1639) is opgelost. Er is op dit moment nog geen oorzaak bekend. Excuses voor het ongemak. [#Liander],twitter,nl,"['stroomstoring', 'hoogkarspel', 'wervershoof', 'postcode', 'opgelost', 'moment', 'oorzaak', 'bekend', 'excuses', 'ongemak', 'liander']","['stroomstor', 'hoogkarspel', 'wervershof', 'postcod', 'opgelost', 'moment', 'oorzak', 'bekend', 'excuses', 'ongemak', 'liander']",0.350000,0.800

## Check words from wordlist in data

In [10]:
#Load wordlist
wordlist = pd.read_excel('Sustainability_Wordlist.xlsx')

wordlist

   Environmental Sustainability Social Sustainability Economic Sustainability
0                   efficiëntie               racisme           bedrijfsgroei
1             energie-efficiënt         discriminatie         groeicapaciteit
2           energie-efficiëntie         discrimineren               productie
3             energy efficiency            gelijkheid          productiegroei
4                 groene stroom           mensenrecht             conjunctuur
..                          ...                   ...                     ...
76                        solar                   NaN                     NaN
77                   greenhouse                   NaN                     NaN
78                          ghg                   NaN                     NaN
79                  klimaatdoel                   NaN                     NaN
80                klimaatdoelen                   NaN                     NaN

[81 rows x 3 columns]

In [11]:
def text_to_words(text):
    '''Transform a string to a list of words,
    removing all punctuation.'''
    text = text.lower()

    p = '!"#$%&\'()*+,-./:;<=>?@[\\]^_`{|}~'
    text = ''.join([ch for ch in text if ch not in p])

    return text.split()

def count_occurences(text, word_list):
    '''Count occurences of words from a list in a text string.'''
    text_list = text_to_words(text)

    intersection = [w for w in text_list if w in word_list]

    return len(intersection)

#Sustainable values
ENV_words = wordlist['Environmental Sustainability'].values
Social_words = wordlist['Social Sustainability'].values
Economic_words = wordlist['Economic Sustainability'].values

#Count the words per environmental/social/economic
DataNL['ENV_words'] = DataNL['Text Clean'].apply(count_occurences, args=(ENV_words, ))
DataNL['Social_words'] = DataNL['Text Clean'].apply(count_occurences, args=(Social_words, ))
DataNL['Economic_words'] = DataNL['Text Clean'].apply(count_occurences, args=(Economic_words, ))

#Label Sustainable Tweets

'''
DataNL['Sustainability'] = np.where((DataNL['ENV_words'] > ((DataNL['Social_words'])) & (DataNL['Economic_words'])) & 
                                    (DataNL['Sentiment'] >= 0), 'Environmental', 
                                     np.where((DataNL['Social_words'] > ((DataNL['ENV_words'])) & (DataNL['Economic_words'])) & 
                                              (DataNL['Sentiment'] >= 0), 'Social', 
                                               np.where((DataNL['Economic_words'] > ((DataNL['ENV_words'])) & (DataNL['Social_words'])) & 
                                                        (DataNL['Sentiment'] >= 0), 'Economic', 'Non-Sustainable')))

'''

DataNL['Sustainability'] = np.where((DataNL['ENV_words'] > ((DataNL['Social_words'])) & (DataNL['Economic_words'])) & 
                                     (DataNL['Sentiment'] >= 0), 'Positive Environmental', 
                                np.where((DataNL['ENV_words'] > ((DataNL['Social_words'])) & (DataNL['Economic_words'])) & 
                                         (DataNL['Sentiment'] < 0), 'Negative Environmental', 
                                    np.where((DataNL['Social_words'] > ((DataNL['ENV_words'])) & (DataNL['Economic_words'])) & 
                                             (DataNL['Sentiment'] >= 0), 'Positive Social', 
                                        np.where((DataNL['Social_words'] > ((DataNL['ENV_words'])) & (DataNL['Economic_words'])) & 
                                                 (DataNL['Sentiment'] < 0), 'Negative Social', 
                                            np.where((DataNL['Economic_words'] > ((DataNL['ENV_words'])) & (DataNL['Social_words'])) & 
                                                     (DataNL['Sentiment'] >= 0), 'Positive Economic', 
                                                np.where((DataNL['Economic_words'] > ((DataNL['ENV_words'])) & (DataNL['Social_words'])) & 
                                                         (DataNL['Sentiment'] < 0), 'Negative Economic', 
                                                    'Non-Sustainable'                                 
                                    ))))))


#New dummy columns to groupby later on

DataNL.loc[DataNL['Sustainability'] == 'Positive Environmental', 'Positive Environmental'] = 1
DataNL.loc[DataNL['Sustainability'] == 'Negative Environmental', 'Negative Environmental'] = 1

DataNL.loc[DataNL['Sustainability'] == 'Positive Social', 'Positive Social'] = 1
DataNL.loc[DataNL['Sustainability'] == 'Negative Social', 'Negative Social'] = 1

DataNL.loc[DataNL['Sustainability'] == 'Positive Economic', 'Positive Economic'] = 1
DataNL.loc[DataNL['Sustainability'] == 'Negative Economic', 'Negative Economic'] = 1


DataNL

,zoekopdracht,datum,bericht tekst,Text Clean,Sentiment,ENV_words,Social_words,Economic_words,Sustainability,Positive Environmental,Negative Environmental,Positive Social,Negative Social,Positive Economic,Negative Economic
0,"""Aalberts N.V."" OR ""AALB""",2021-03-18 11:53,$[AALB] #AALBERTS @aalbertsindustr - Dagelijks: AALBERTS NV maakt een erg sterke bullish trend door. Traders kunnen overwegen alleen longposities te handelen (op moment van aankoop) zolang de koers... https://t.co/hOiR5KPSeX,"['aalb', 'aalberts', 'dagelijks', 'aalberts', 'nv', 'maakt', 'erg', 'sterke', 'bullish', 'trend', 'traders', 'overwegen', 'alleen', 'longposities', 'handelen', 'moment', 'aankoop', 'zolang', 'koers']",0.388333,0,0,0,Non-Sustainable,NaN,NaN,NaN,NaN,NaN,NaN
1,"""Aalberts N.V."" OR ""AALB""",2021-03-18 11:53,$[AALB] #AALBERTS - Dagelijks: AALBERTS NV maakt een erg sterke bullish trend door. Traders kunnen overwegen alleen longposities te handelen (op moment van aankoop) zolang de koers... https://t.co/dZWInNPIYj,"['aalb', 'aalberts', 'dagelijks', 'aalberts', 'nv', 'maakt', 'erg', 'sterke', 'bullish', 'trend', 'traders', 'overwegen', 'alleen', 'longposities', 'handelen', 'moment', 'aankoop', 'zolang', 'koers']",0.388333,0,0,0,Non-Sustainable,NaN,NaN,NaN,NaN,NaN,NaN
2,"""Aalberts N.V."" OR ""AALB""",2020-11-05 14:53,"Zojuist de [AALB] dec20 30 call (optietip 176) verkocht voor €3,25. Gekocht voor €1,10. Had achteraf gezien beter gekund, maar je kunt toch niet echt ontevreden zijn met 195% winst. https://t.co/OsAvGABjst","['zojuist', 'aalb', 'dec', 'call', 'optietip', 'verkocht', 'gekocht', 'achteraf', 'gezien', 'beter', 'gekund', 'kunt', 'echt', 'ontevreden', 'winst']",0.125000,0,0,0,Non-Sustainable,NaN,NaN,NaN,NaN,NaN,NaN
3,"""Aalberts N.V."" OR ""AALB""",2020-08-11 11:41,#Aalberts [#AALB] laat een mooie uitbraak zien boven de 200MA curve. Vanaf 20-07-20 in portfolio. Target €35.00 https://t.co/FxvCgNF88F,"['aalberts', 'aalb', 'laat', 'mooie', 'uitbraak', 'zien', 'boven', 'ma', 'curve', 'vanaf', 'portfolio', 'target']",0.200000,0,0,0,Non-Sustainable,NaN,NaN,NaN,NaN,NaN,NaN
4,"""Aalberts N.V."" OR ""AALB""",2020-04-01 16:43,Koenie's Corona Crash bodem kooplijstje: 1-ABN 2-AGN 3-[AALB] 4-ASML 5-ABI 6-MT 7-DSM 8-GLPG 9-HEI 10-ING 11-LIGHT 12-PHI 13-RDSA 14-UNIA 15-DEL2 Not Yet...W8 4 iT!,"['koenie', 'corona', 'crash', 'bodem', 'kooplijstje', 'abn', 'agn', 'aalb', 'asml', 'abi', 'mt', 'dsm', 'glpg', 'hei', 'ing', 'light', 'phi', 'rdsa', 'unia', 'del', 'not', 'yet', 'it']",0.000000,0,0,0,Non-Sustainable,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
128995,"""Alliander"" OR ""Liander"" OR ""Qirion"" OR ""Kenter""",2019-07-13 12:10,"https://t.co/NYnpVpVauf | #Vacature #Beleidsadviseur #Laagspanning | [Liander] | Landelijk | Ben jij de nauwkeurige, gedreven Beleidsadviseur die we zoeken? Kom ons team versterken! #Solliciteer #JobsinEnergy https://t.co/mHSftqxbtG","['vacature', 'beleidsadviseur', 'laagspanning', 'liander', 'landelijk', 'jij', 'nauwkeurige', 'gedreven', 'beleidsadviseur', 'we', 'zoeken', 'kom', 'team', 'versterken', 'solliciteer', 'jobsinenergy']",0.500000,0,0,0,Non-Sustainable,NaN,NaN,NaN,NaN,NaN,NaN
128996,"""Alliander"" OR ""Liander"" OR ""Qirion"" OR ""Kenter""",2019-07-13 11:30,https://t.co/mV9RK1qWGD | #Vacature #HSE #Business #Partner | [Liander] | Amsterdam | Ben jij die HSE professional met ervaring binnen een projectorganisatie? #Solliciteer #JobsinEnergy https://t.co/vbTEri0EAS,"['vacature', 'hse', 'business', 'partner', 'liander', 'amsterdam', 'jij', 'hse', 'professional', 'ervaring', 'binnen', 'projectorganisatie', 'solliciteer', 'jobsinenergy']",0.000000,0,0,1,Positive Economic,NaN,NaN,NaN,NaN,1.0,NaN
128997,"""Alliander"" OR ""Liander"" OR ""Qirion"" OR ""Kenter""",2019-07-13 11:00,https://t.co/BTP2UnDA0f | #Consultant – rol #Scrummaster | [Liander] | Duiven | Ben jij de pragmatische Scrummaster die we zoeken? Kom ons team versterken! | #JobsinEnergy | #Solliciteer https://t.co/1wfjeGqaTD,"['consultant', 'rol', 'scrummaster', 'liander', 'duiven', 'jij', 'pragmatische', 'scrummaster', 'we', 'zoeken', 'kom', 'team', 'versterken', 'jobsinenergy', 'solliciteer']",0.000000,0,0,0,Non-Sustainable,NaN,NaN,NaN,NaN,NaN,NaN
128998,"""Alliander"" OR ""Liander"" OR ""Qirion"" OR ""Kenter""",2019-07-13 10:22,Onderhoudsmonteur machines / installaties – Leeuwarden – [Alliander] – Leeuwarden https://t.co/210Z26FpnL,"['onderhoudsmonteur', 'machines', 'installaties', 'leeuwarden', 'alliander', 'leeuwarden']",0.000000,0,0,0,Non-Sustainable,NaN,NaN,NaN,NaN,NaN,NaN
128999,"""Alliander"" OR ""Liander"" OR ""Qirion"" OR ""Kenter""",2019-07-13 10:04,#Stroomstoring #Hoogkarspel #Wervershoof (postcode 1616 en 1639) is opgelost. Er is op dit moment nog geen oorzaak bekend. Excuses voor het ongemak. [#Liander],"['stroomstoring', 'hoogkarspel', 'wervershoof', 'postcode', 'opgelost', 'moment', 'oorzaak', 'bekend', 'excuses', 'ongemak', 'liander']",0.350000,0,0,0,Non-Sustainable,NaN,NaN,NaN,NaN,NaN,NaN

In [12]:
DataNL['Positive Environmental'].sum()

10554.0

In [13]:
#Total number of Tweets per company
TotalTweets = DataNL.groupby(['zoekopdracht']).size().reset_index(name='Total number of Tweets')

#Number of sustainable Tweets per company
SustTweets = DataNL[['zoekopdracht', 
                     'Positive Environmental', 
                     'Negative Environmental', 
                     'Positive Social', 
                     'Negative Social', 
                     'Positive Economic', 
                     'Negative Economic']]

SustTweets = SustTweets.groupby('zoekopdracht').sum() #Get total number of sust tweets, for percentage use .mean()
SustTweets['Total Sustainability Tweets'] = (SustTweets['Positive Environmental'] + 
                                             SustTweets['Negative Environmental'] + 
                                             SustTweets['Positive Social'] + 
                                             SustTweets['Negative Social'] + 
                                             SustTweets['Positive Economic'] +                                              
                                             SustTweets['Negative Economic']
                                            )

#Merge datasets
Tweets = pd.merge(SustTweets, TotalTweets, on = 'zoekopdracht', how = 'inner')

#Calculate index
Tweets['Positive Index'] = ((Tweets['Positive Environmental'] + 
                            Tweets['Positive Social'] + 
                            Tweets['Positive Economic']) /
                            Tweets['Total Sustainability Tweets']) * 100
Tweets['Sustainability Index'] = (Tweets['Total Sustainability Tweets'] / Tweets['Total number of Tweets'])*100
Tweets['Environmental Index'] = ((Tweets['Positive Environmental'] + Tweets['Negative Environmental']) / 
                                  Tweets['Total Sustainability Tweets']) * 100
Tweets['Social Index'] = ((Tweets['Positive Social'] + Tweets['Negative Social']) / 
                           Tweets['Total Sustainability Tweets']) * 100
Tweets['Economic Index'] = ((Tweets['Positive Economic'] + Tweets['Negative Economic']) / 
                             Tweets['Total Sustainability Tweets']) * 100

#Rename column for merge
Tweets = Tweets.rename(columns={'zoekopdracht': 'Search Query'})

Tweets2 = Tweets[['Search Query', 
                  'Total number of Tweets',
                  'Total Sustainability Tweets',
                  'Positive Index',
                  'Sustainability Index',
                  'Environmental Index',
                  'Social Index',
                  'Economic Index']]

Tweets2

,Search Query,Total number of Tweets,Total Sustainability Tweets,Positive Index,Sustainability Index,Environmental Index,Social Index,Economic Index
0,"""ABN AMRO Group"" OR ""ABN"" OR ""ABN AMRO""",8748,1424.0,80.898876,16.278006,40.941011,7.092697,51.966292
1,"""AEGON"" OR ""AGN""",4057,202.0,92.079208,4.979049,7.920792,1.980198,90.099010
2,"""Aalberts N.V."" OR ""AALB""",60,0.0,NaN,0.000000,NaN,NaN,NaN
3,"""Accell Group"" OR ""ACCEL""",485,25.0,52.000000,5.154639,4.000000,0.000000,96.000000
4,"""Accsys Technologies"" OR ""AXS"" OR ""Accsys""",804,33.0,84.848485,4.104478,51.515152,0.000000,48.484848
5,"""Adyen"" OR ""ADYEN""",6728,353.0,81.869688,5.246730,7.082153,4.249292,88.668555
6,"""Air France-KLM"" OR ""Air France"" OR ""KLM""",8050,750.0,66.266667,9.316770,34.266667,14.533333,51.200000
7,"""AkzoNobel"" OR ""AKZA""",6061,772.0,81.476684,12.737172,25.647668,41.450777,32.901554
8,"""Alfen"" OR ""ALFEN""",1934,167.0,83.233533,8.634953,72.455090,8.982036,18.562874
9,"""Alliander"" OR ""Liander"" OR ""Qirion"" OR ""Kenter""",8671,1097.0,87.420237,12.651367,80.309936,3.828624,15.861440
10,"""Altice Europe"" OR ""ATC"" OR ""Altice""",6518,238.0,80.672269,3.651427,8.823529,38.655462,52.521008
11,"""Coca-Cola European Partners"" OR ""Coca-Cola"" OR ""Coca Cola"" OR ""CCE""",5927,569.0,75.395431,9.600135,37.082601,24.253076,38.664323
12,"""ENGIE""",7278,1730.0,86.647399,23.770267,86.184971,2.832370,10.982659
13,"""Eneco""",87,13.0,92.307692,14.942529,84.615385,15.384615,0.000000
14,"""Essent""",9070,1388.0,84.365994,15.303197,81.988473,3.818444,14.193084
15,"""Greenchoice""",9500,2276.0,82.513181,23.957895,92.574692,1.537786,5.887522
16,"""Koninklijke Ahold"" OR ""Ahold"" OR ""AD"" OR ""Ahold Delhaize""",8640,669.0,79.820628,7.743056,15.844544,24.813154,59.342302
17,"""Nederlandse Energie Maatschappij""",3521,218.0,89.449541,6.191423,43.577982,2.293578,54.128440
18,"""Oxxio""",9099,408.0,80.147059,4.484009,29.656863,5.147059,65.196078
19,"""Vandebron""",8348,2112.0,79.166667,25.299473,84.564394,1.515152,13.920455
20,"""Vattenfall"" OR ""NUON""",8245,1922.0,80.437045,23.311098,91.727367,1.352758,6.919875
21,"""shell""",7169,2431.0,71.698889,33.909890,89.387084,3.331962,7.280954

In [14]:
Tweets

,Search Query,Positive Environmental,Negative Environmental,Positive Social,Negative Social,Positive Economic,Negative Economic,Total Sustainability Tweets,Total number of Tweets,Positive Index,Sustainability Index,Environmental Index,Social Index,Economic Index
0,"""ABN AMRO Group"" OR ""ABN"" OR ""ABN AMRO""",472.0,111.0,71.0,30.0,609.0,131.0,1424.0,8748,80.898876,16.278006,40.941011,7.092697,51.966292
1,"""AEGON"" OR ""AGN""",14.0,2.0,4.0,0.0,168.0,14.0,202.0,4057,92.079208,4.979049,7.920792,1.980198,90.099010
2,"""Aalberts N.V."" OR ""AALB""",0.0,0.0,0.0,0.0,0.0,0.0,0.0,60,NaN,0.000000,NaN,NaN,NaN
3,"""Accell Group"" OR ""ACCEL""",1.0,0.0,0.0,0.0,12.0,12.0,25.0,485,52.000000,5.154639,4.000000,0.000000,96.000000
4,"""Accsys Technologies"" OR ""AXS"" OR ""Accsys""",13.0,4.0,0.0,0.0,15.0,1.0,33.0,804,84.848485,4.104478,51.515152,0.000000,48.484848
5,"""Adyen"" OR ""ADYEN""",20.0,5.0,14.0,1.0,255.0,58.0,353.0,6728,81.869688,5.246730,7.082153,4.249292,88.668555
6,"""Air France-KLM"" OR ""Air France"" OR ""KLM""",181.0,76.0,51.0,58.0,265.0,119.0,750.0,8050,66.266667,9.316770,34.266667,14.533333,51.200000
7,"""AkzoNobel"" OR ""AKZA""",167.0,31.0,246.0,74.0,216.0,38.0,772.0,6061,81.476684,12.737172,25.647668,41.450777,32.901554
8,"""Alfen"" OR ""ALFEN""",105.0,16.0,13.0,2.0,21.0,10.0,167.0,1934,83.233533,8.634953,72.455090,8.982036,18.562874
9,"""Alliander"" OR ""Liander"" OR ""Qirion"" OR ""Kenter""",761.0,120.0,37.0,5.0,161.0,13.0,1097.0,8671,87.420237,12.651367,80.309936,3.828624,15.861440
10,"""Altice Europe"" OR ""ATC"" OR ""Altice""",14.0,7.0,78.0,14.0,100.0,25.0,238.0,6518,80.672269,3.651427,8.823529,38.655462,52.521008
11,"""Coca-Cola European Partners"" OR ""Coca-Cola"" OR ""Coca Cola"" OR ""CCE""",165.0,46.0,91.0,47.0,173.0,47.0,569.0,5927,75.395431,9.600135,37.082601,24.253076,38.664323
12,"""ENGIE""",1283.0,208.0,46.0,3.0,170.0,20.0,1730.0,7278,86.647399,23.770267,86.184971,2.832370,10.982659
13,"""Eneco""",10.0,1.0,2.0,0.0,0.0,0.0,13.0,87,92.307692,14.942529,84.615385,15.384615,0.000000
14,"""Essent""",979.0,159.0,32.0,21.0,160.0,37.0,1388.0,9070,84.365994,15.303197,81.988473,3.818444,14.193084
15,"""Greenchoice""",1738.0,369.0,33.0,2.0,107.0,27.0,2276.0,9500,82.513181,23.957895,92.574692,1.537786,5.887522
16,"""Koninklijke Ahold"" OR ""Ahold"" OR ""AD"" OR ""Ahold Delhaize""",95.0,11.0,136.0,30.0,303.0,94.0,669.0,8640,79.820628,7.743056,15.844544,24.813154,59.342302
17,"""Nederlandse Energie Maatschappij""",83.0,12.0,4.0,1.0,108.0,10.0,218.0,3521,89.449541,6.191423,43.577982,2.293578,54.128440
18,"""Oxxio""",102.0,19.0,13.0,8.0,212.0,54.0,408.0,9099,80.147059,4.484009,29.656863,5.147059,65.196078
19,"""Vandebron""",1374.0,412.0,27.0,5.0,271.0,23.0,2112.0,8348,79.166667,25.299473,84.564394,1.515152,13.920455
20,"""Vattenfall"" OR ""NUON""",1425.0,338.0,19.0,7.0,102.0,31.0,1922.0,8245,80.437045,23.311098,91.727367,1.352758,6.919875
21,"""shell""",1552.0,621.0,62.0,19.0,129.0,48.0,2431.0,7169,71.698889,33.909890,89.387084,3.331962,7.280954

## Merge dataframe with SearchQuery to match companies with their industry

In [15]:
#Read Search Query file
Companies = pd.read_excel('/Users/Marcel/Desktop/Master Digital Driven Business/Master Project/Data Collection/MasterProject_CoostoSearchQuery.xlsx')

#Select only desired columns
Companies2 = Companies[['Search Query', 'Organisation', 'Industry']]

#Merge and create final dataset
finaldf = pd.merge(Companies2, Tweets2, on = 'Search Query', how = 'inner')

#Delete unnecessary columns
del finaldf['Search Query']

finaldf

,Organisation,Industry,Total number of Tweets,Total Sustainability Tweets,Positive Index,Sustainability Index,Environmental Index,Social Index,Economic Index
0,Aalberts N.V.,Industrie,60,0.0,NaN,0.000000,NaN,NaN,NaN
1,ABN AMRO Group,Financiële dienstverleners,8748,1424.0,80.898876,16.278006,40.941011,7.092697,51.966292
2,Accell Group,Consumenten goederen,485,25.0,52.000000,5.154639,4.000000,0.000000,96.000000
3,Accsys Technologies,Chemie,804,33.0,84.848485,4.104478,51.515152,0.000000,48.484848
4,Adyen,Technologie,6728,353.0,81.869688,5.246730,7.082153,4.249292,88.668555
5,AEGON,Financiële dienstverleners,4057,202.0,92.079208,4.979049,7.920792,1.980198,90.099010
6,Koninklijke Ahold / Ahold Delhaize,Detail- & groothandel,8640,669.0,79.820628,7.743056,15.844544,24.813154,59.342302
7,Air France-KLM,Transport & logistiek,8050,750.0,66.266667,9.316770,34.266667,14.533333,51.200000
8,AkzoNobel,Chemie,6061,772.0,81.476684,12.737172,25.647668,41.450777,32.901554
9,Alfen,Technologie,1934,167.0,83.233533,8.634953,72.455090,8.982036,18.562874
10,Altice Europe,Telecommunicatie,6518,238.0,80.672269,3.651427,8.823529,38.655462,52.521008
11,Coca-Cola European Partners,Voeding & drank,5927,569.0,75.395431,9.600135,37.082601,24.253076,38.664323
12,Royal Dutch Shell A,Olie & Gas,7169,2431.0,71.698889,33.909890,89.387084,3.331962,7.280954
13,Greenchoice,Energie,9500,2276.0,82.513181,23.957895,92.574692,1.537786,5.887522
14,Vattenfall,Energie,8245,1922.0,80.437045,23.311098,91.727367,1.352758,6.919875
15,Vandebron,Energie,8348,2112.0,79.166667,25.299473,84.564394,1.515152,13.920455
16,Eneco,Energie,87,13.0,92.307692,14.942529,84.615385,15.384615,0.000000
17,Essent,Energie,9070,1388.0,84.365994,15.303197,81.988473,3.818444,14.193084
18,ENGIE,Energie,7278,1730.0,86.647399,23.770267,86.184971,2.832370,10.982659
19,NLE (Nederlande Energie Maatschappij),Energie,3521,218.0,89.449541,6.191423,43.577982,2.293578,54.128440
20,Oxxio,Energie,9099,408.0,80.147059,4.484009,29.656863,5.147059,65.196078
21,Alliander,Energie,8671,1097.0,87.420237,12.651367,80.309936,3.828624,15.861440

## Vectorize

In [218]:
#DataNL2 = pd.read_csv('Coosto_Clean_NL.csv')

In [12]:
DataNL.set_index('zoekopdracht')
#del DataNL['Unnamed: 0']
DataNL2 = DataNL.sample(frac=1).reset_index(drop=True).head(65000)
#DataNL3 = DataNL.head(65000)
DataNL2

,zoekopdracht,datum,bericht tekst,type bron,Lang,Text Clean,Stemmed Clean,Subjectivity,Sentiment,Subjectivity
0,"""Coca-Cola European Partners"" OR ""Coca-Cola"" OR ""Coca Cola"" OR ""CCE""",2020-12-18 18:45,Helft van de banen bij [Coca-Cola] België bedreigd https://t.co/hT6UDHhZBb,twitter,nl,"['helft', 'banen', 'coca', 'cola', 'belgi', 'bedreigd']","['helft', 'ban', 'coca', 'cola', 'belgi', 'bedreigd']",0.00,0.000000,0.00
1,"""Essent""",2018-02-27 06:37,Parttime verkoopadviseur voor [Essent] in de 'Shop-in-Shop' - YoungCapital - Den Bosch https://t.co/lfOTMQn5xN,twitter,nl,"['parttime', 'verkoopadviseur', 'essent', 'shop', 'shop', 'youngcapital', 'den', 'bosch']","['parttim', 'verkoopadviseur', 'essent', 'shop', 'shop', 'youngcapital', 'den', 'bosch']",0.00,0.000000,0.00
2,"""Vattenfall"" OR ""NUON""",2021-01-15 07:00,Sloop [NUON]-gebouw https://t.co/iPNTpS90H4,twitter,nl,"['sloop', 'nuon', 'gebouw']","['slop', 'nuon', 'gebouw']",0.00,0.000000,0.00
3,"""ENGIE""",2018-10-22 16:47,"""Weinig elektrische wagens op Belgische wegen""...maar met het [ENGIE] project EV Boost komen er 900 bij tegen 2020 ! https://t.co/4PhSWZv4vE via @destandaard",twitter,nl,"['weinig', 'elektrische', 'wagens', 'belgische', 'wegen', 'engie', 'project', 'ev', 'boost', 'komen', 'via']","['weinig', 'elektrisch', 'wagen', 'belgisch', 'weg', 'engie', 'project', 'ev', 'boost', 'kom', 'via']",0.00,0.000000,0.00
4,"""Oxxio""",2015-08-31 18:19,[@Oxxio] als ik me aanmeld voor oxxio Hoe lang duurt het voor mn oude contract is opgezegd en overgezet is ?,twitter,nl,"['aanmeld', 'oxxio', 'lang', 'duurt', 'mn', 'oude', 'contract', 'opgezegd', 'overgezet']","['aanmeld', 'oxxio', 'lang', 'duurt', 'mn', 'oud', 'contract', 'opgezegd', 'overgezet']",0.40,-0.050000,0.40
...,...,...,...,...,...,...,...,...,...,...
64995,"""Vandebron""",2015-03-06 09:07,Solar Magazine - [#Vandebron] lanceert platform (#marktplaats) voor verkoop stroom van #zonnepanelen aan buren http://t.co/YaTRTFJ2p5,twitter,nl,"['solar', 'magazine', 'vandebron', 'lanceert', 'platform', 'marktplaats', 'verkoop', 'stroom', 'zonnepanelen', 'buren']","['solar', 'magazin', 'vandebron', 'lanceert', 'platform', 'marktplat', 'verkop', 'strom', 'zonnepanel', 'bur']",0.00,0.000000,0.00
64996,"""AEGON"" OR ""AGN""",2016-10-17 16:28,[#AEGON] Aegon aan kop op lager Damrak: Rentevrees en tegenvallende bedrijfscijfers zetten aandelenkoersen Euro... https://t.co/lCqOIGxCs2,twitter,nl,"['aegon', 'aegon', 'kop', 'lager', 'damrak', 'rentevrees', 'tegenvallende', 'bedrijfscijfers', 'zetten', 'aandelenkoersen', 'euro']","['aegon', 'aegon', 'kop', 'lager', 'damrak', 'rentevres', 'tegenvall', 'bedrijfscijfer', 'zet', 'aandelenkoers', 'euro']",0.00,0.000000,0.00
64997,"""ABN AMRO Group"" OR ""ABN"" OR ""ABN AMRO""",2020-12-17 06:00,[ABN AMRO]: veerkracht doorslaggevend ROTTERDAM – De coronacrisis zorgt voor grote verschillen tussen sectoren d... https://t.co/Gs4bfD0ral,twitter,nl,"['abn', 'amro', 'veerkracht', 'doorslaggevend', 'rotterdam', 'coronacrisis', 'zorgt', 'grote', 'verschillen', 'tussen', 'sectoren']","['abn', 'amro', 'veerkracht', 'doorslaggev', 'rotterdam', 'coronacrisis', 'zorgt', 'grot', 'verschill', 'tuss', 'sector']",0.65,0.283333,0.65
64998,"""Coca-Cola European Partners"" OR ""Coca-Cola"" OR ""Coca Cola"" OR ""CCE""",2019-03-26 16:50,Roemenie wil als EU-voorzitter werken aan het herstel van vertrouwen van burgers in de EU. https://t.co/9YPZta3ssy En tegelijkertijd laat zij zich sponsoren door [Coca-Cola]... https://t.co/Kx6qyGz9WI,twitter,nl,"['roemenie', 'eu', 'voorzitter', 'werken', 'herstel', 'vertrouwen', 'burgers', 'eu', 'tegelijkertijd', 'laat', 'sponsoren', 'coca', 'cola']","['roemenie', 'eu', 'voorzitter', 'werk', 'herstel', 'vertrouw', 'burger', 'eu', 'tegelijkertijd', 'lat', 'sponsor', 'coca', 'cola']",0.60,-0.300000,0.60
64999,"""Vandebron""",2018-03-17 21:00,"Wil je groene energie? Omdat ik klant ben bij [@Vandebron], mag ik mijn vrienden € 75,- cadeau doen. Meld je hier aan: https://t.co/A8kLifIiRu",twitter,nl,"['groene', 'energie', 'klant', 'mag', 'vrienden', 'cadeau', 'meld']","['groen', 'energie', 'klant', 'mag', 'vriend', 'cadeau', 'meld']",0.60,0.150000,0.60

In [11]:
#Get number of words

from sklearn.feature_extraction.text import CountVectorizer

def clean_text(text):
    #Clean text
    text = re.sub(r"(?:\@|http?\://|https?\://|www)\S+", "", text) #Remove http links
    text = re.sub("[^a-zA-Z]", " ", text)# Search for all non-letters # Replace all non-letters with spaces
    text = text.lower() #Lower text
    text = re.sub('\[.*?\]', '', text)
    #text = re.sub(r"(?:\@|http?\://|https?\://|www)\S+", "", text) #Remove http links
    text = re.sub('[%s]' % re.escape(string.punctuation), '', text)
    text = re.sub('\w*\d\w*', '', text) #Remove numbers and text with numbers   
    text = ''.join(c for c in text if c not in emoji.UNICODE_EMOJI) #Remove Emojis
    text = re.sub('\n', '', text) #Remove \n
    text = re.sub('€', '', text) #Remove €
    
    # tokenize text and remove puncutation
    text = [word.strip(string.punctuation) for word in text.split(" ")]

    #Remove stopwords
    #Dutch stop words
    stop = nltk.corpus.stopwords.words('dutch')
    text = [word for word in text if word not in stop]    
    
    # remove empty tokens and tokens with 1 
    text = [t for t in text if len(t) > 1]    
    
    return text

#Vectorize words
countVectorizer = CountVectorizer(analyzer=clean_text) #No word stemming in clean_text
countVector = countVectorizer.fit_transform(DataNL['bericht tekst'])
print('{} Number of tweets has {} words'.format(countVector.shape[0], countVector.shape[1]))

#Dataframe of words
count_vect_df = pd.DataFrame(countVector.toarray(), columns=countVectorizer.get_feature_names())
count_vect_df.head()

129000 Number of tweets has 75227 words

,aa,aaaaaaaaaaaaa,aaaaaaaargh,aaaaand,aaaargh,aaachh,aaah,aaansluiting,aaanvang,aaay,...,zwommen,zyn,zz,zzoomm,zzp,zzpay,zzpers,zzpol,zzzzz,zzzzzzzzzzzzz
0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [13]:
#Select only environmental words
ENV_vectors = count_vect_df[count_vect_df.columns.intersection(ENV_words)]

#Select SQ, text and sentiment from data
smallset = DataNL[['zoekopdracht', 'datum', 'Sentiment']]

#Merge dataframes together
ENVcount = pd.concat([smallset, ENV_vectors], axis=1).reindex(smallset.index)

ENVcount

,zoekopdracht,datum,Sentiment,aardgasloos,biobrandstof,biodiversiteit,brandstof,brandstoffen,broeikaseffect,broeikasgas,...,warmteterugwinning,waterstof,windenergie,windmolen,windmolens,windpark,windparken,zonnepaneel,zonnepanelen,zonnepark
0,"""Aalberts N.V."" OR ""AALB""",2021-03-18 11:53,0.388333,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,"""Aalberts N.V."" OR ""AALB""",2021-03-18 11:53,0.388333,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,"""Aalberts N.V."" OR ""AALB""",2020-11-05 14:53,0.125000,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,"""Aalberts N.V."" OR ""AALB""",2020-08-11 11:41,0.200000,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,"""Aalberts N.V."" OR ""AALB""",2020-04-01 16:43,0.000000,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
128995,"""Alliander"" OR ""Liander"" OR ""Qirion"" OR ""Kenter""",2019-07-13 12:10,0.500000,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
128996,"""Alliander"" OR ""Liander"" OR ""Qirion"" OR ""Kenter""",2019-07-13 11:30,0.000000,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
128997,"""Alliander"" OR ""Liander"" OR ""Qirion"" OR ""Kenter""",2019-07-13 11:00,0.000000,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
128998,"""Alliander"" OR ""Liander"" OR ""Qirion"" OR ""Kenter""",2019-07-13 10:22,0.000000,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
128999,"""Alliander"" OR ""Liander"" OR ""Qirion"" OR ""Kenter""",2019-07-13 10:04,0.350000,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

## Sum most frequent environmental words with a positive sentiment per company

In [98]:
#Subset based on sentiment
PosENV = ENVcount[(ENVcount['Sentiment'] >= 0)]

#Delete Sentiment column
del PosENV['Sentiment']

#Groupby search query
PosENV = PosENV.groupby('zoekopdracht').sum() #Get sum of words used

#Reset index
PosENV.reset_index(inplace = True)

#Rename column for merge
PosENV = PosENV.rename(columns={'zoekopdracht': 'Search Query'})

#Merge and create final dataset
finalPosENV = pd.merge(Companies2, PosENV, on = 'Search Query', how = 'inner')

#Delete unnecessary columns
del finalPosENV['Search Query']

#Non-numeric to index
#finalPosENV.set_index(['Organisation', 'Industry'], inplace=True)            

finalPosENV

,Organisation,Industry,aardgasloos,biobrandstof,biodiversiteit,brandstof,brandstoffen,broeikaseffect,broeikasgas,circulair,...,warmteterugwinning,waterstof,windenergie,windmolen,windmolens,windpark,windparken,zonnepaneel,zonnepanelen,zonnepark
0,Aalberts N.V.,Industrie,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,ABN AMRO Group,Financiële dienstverleners,0,11,2,8,3,0,0,23,...,0,10,0,0,1,4,0,0,0,0
2,Accell Group,Consumenten goederen,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1,0
3,Accsys Technologies,Chemie,0,0,0,0,0,0,0,0,...,0,1,0,0,0,0,0,0,0,0
4,Adyen,Technologie,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
5,AEGON,Financiële dienstverleners,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,4,0
6,Koninklijke Ahold / Ahold Delhaize,Detail- & groothandel,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
7,Air France-KLM,Transport & logistiek,0,2,1,17,1,0,0,0,...,0,2,0,0,2,0,0,0,2,0
8,AkzoNobel,Chemie,0,2,1,1,0,3,0,3,...,0,28,3,1,0,16,1,0,3,0
9,Alfen,Technologie,0,0,0,0,0,0,0,0,...,0,0,17,0,0,7,2,0,17,18
10,Altice Europe,Telecommunicatie,0,0,0,1,0,0,0,0,...,0,2,0,0,0,0,0,0,0,0
11,Coca-Cola European Partners,Voeding & drank,0,0,1,3,0,0,0,4,...,0,0,0,0,1,0,0,0,17,1
12,Royal Dutch Shell A,Olie & Gas,1,3,4,23,30,0,2,2,...,0,60,21,1,25,70,2,0,5,21
13,Greenchoice,Energie,8,0,6,1,0,0,0,20,...,0,5,107,69,50,87,1,10,455,82
14,Vattenfall,Energie,0,0,2,5,1,0,0,3,...,0,28,110,6,112,423,73,0,67,108
15,Vandebron,Energie,0,0,0,2,0,0,0,3,...,0,1,100,30,35,45,1,3,171,17
16,Eneco,Energie,0,0,0,0,0,0,0,0,...,0,0,0,0,0,6,1,0,1,0
17,Essent,Energie,0,0,0,5,3,0,1,2,...,0,11,11,3,10,14,3,13,480,2
18,ENGIE,Energie,0,0,2,0,5,0,0,44,...,16,76,19,5,28,10,1,4,211,173
19,NLE (Nederlande Energie Maatschappij),Energie,0,0,0,0,0,0,0,0,...,0,0,1,3,4,0,0,0,72,0
20,Oxxio,Energie,0,0,0,1,0,0,0,0,...,0,0,21,0,1,0,0,2,42,0
21,Alliander,Energie,5,0,3,1,0,0,0,4,...,0,67,5,0,11,10,6,0,178,35

In [43]:
rows_index = finalPosENV.max(axis=1).sort_values(ascending=False).index
col_index = finalPosENV.max().sort_values(ascending=False).index
new_df = finalPosENV.loc[rows_index,col_index]
new_df

,,zonnepanelen,olie,duurzame,windpark,energietransitie,solar,duurzaam,klimaatzaak,kolencentrale,circulaire,...,broeikaseffect,energiezuinig,geothermie,ecologisch,broeikasgas,energieprestatie,greenhouse,klimaatverdrag,koolstofdioxide,renewables
Organisation,Industry,,,,,,,,,,,,,,,,,,,,,
Essent,Energie,480,3,102,14,118,103,83,1,9,1,...,0,2,0,0,1,0,0,0,0,0
Royal Dutch Shell A,Olie & Gas,5,478,69,70,48,6,62,253,1,1,...,0,0,1,1,2,0,1,1,1,1
Greenchoice,Energie,455,1,436,87,152,80,284,1,1,7,...,0,2,0,2,0,0,0,0,0,1
Vattenfall,Energie,67,3,113,423,71,300,150,1,23,0,...,0,0,1,0,0,0,0,0,0,1
Vandebron,Energie,171,1,398,45,64,43,213,2,241,6,...,0,0,0,0,0,0,0,0,0,0
ENGIE,Energie,211,1,390,10,135,89,247,0,2,45,...,0,3,3,0,0,0,0,0,0,1
Alliander,Energie,178,1,25,10,326,115,231,0,0,4,...,0,0,0,1,0,0,0,0,0,0
ABN AMRO Group,Financiële dienstverleners,0,8,159,4,16,0,92,0,0,197,...,0,0,0,0,0,2,0,0,0,0
NLE (Nederlande Energie Maatschappij),Energie,72,0,3,0,0,11,4,0,0,0,...,0,0,0,0,0,0,0,0,0,0
Air France-KLM,Transport & logistiek,2,1,54,0,2,0,35,0,0,2,...,0,0,0,0,0,0,0,0,0,0
Oxxio,Energie,42,1,2,0,0,0,30,0,0,0,...,0,0,0,0,0,0,0,0,0,0
Coca-Cola European Partners,Voeding & drank,17,2,24,0,0,0,14,0,0,2,...,0,0,0,0,0,0,0,1,0,0
AkzoNobel,Chemie,3,10,30,16,10,0,19,0,0,11,...,3,0,0,0,0,0,0,0,0,0
Koninklijke Ahold / Ahold Delhaize,Detail- & groothandel,0,17,18,0,3,0,7,0,0,0,...,0,0,0,0,0,0,0,0,0,0
Alfen,Technologie,17,4,9,7,18,11,5,0,0,0,...,0,0,0,0,0,0,0,0,0,0
Adyen,Technologie,0,13,5,0,1,1,1,0,0,0,...,0,0,0,0,0,0,0,0,0,0
Altice Europe,Telecommunicatie,0,9,1,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
Accsys Technologies,Chemie,0,0,6,0,0,0,6,0,0,0,...,0,0,0,0,0,0,0,0,0,0
Eneco,Energie,1,0,0,6,0,0,1,0,0,0,...,0,0,0,0,0,0,0,0,0,0
AEGON,Financiële dienstverleners,4,1,1,0,0,0,2,0,0,0,...,0,0,0,0,0,0,0,0,0,0
Accell Group,Consumenten goederen,1,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
Aalberts N.V.,Industrie,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

## Select company and sort values

In [97]:
#Select specific company
PosENVShell = finalPosENV[(finalPosENV['Organisation'] == 'Royal Dutch Shell A')]

#Delete Industry column
del PosENVShell['Industry']
del PosENVShell['Organisation']

#Transpose (Switch rows and columns)
PosENVShell = PosENVShell.T.rename_axis('Words', axis=1)

#Rename column to company
PosENVShell.rename(columns={ PosENVShell.columns[0]: "Royal Dutch Shell A" }, inplace = True)

#Sort values
PosENVShell.sort_values(by = 'Royal Dutch Shell A', ascending = False, inplace = True)

PosENVShell

Words               Royal Dutch Shell A
olie                                478
klimaatzaak                         253
klimaatverandering                  121
uitstoot                            116
klimaat                             113
fossiele                             84
windpark                             70
duurzame                             69
fossiel                              63
duurzaam                             62
waterstof                            60
olievervuiling                       57
milieu                               54
energietransitie                     48
klimaatakkoord                       30
brandstoffen                         30
windmolens                           25
brandstof                            23
transitie                            21
windenergie                          21
zonnepark                            21
duurzaamheid                         19
klimaatdoelen                        18
klimaatdoel                          17
verduurzaming                        14
verduurzamen                         12
hernieuwbare                         11
kernenergie                           9
solar                                 6
zonnepanelen                          5
hernieuwbaar                          5
klimaatneutraal                       4
biodiversiteit                        4
biobrandstof                          3
windparken                            2
broeikasgas                           2
circulair                             2
energieneutraal                       2
circulaire                            1
ecologisch                            1
windmolen                             1
renewables                            1
ecosysteem                            1
koolstofdioxide                       1
kolencentrale                         1
klimaatverdrag                        1
geothermie                            1
greenhouse                            1
aardgasloos                           1
recyclen                              0
energieakkoord                        0
warmtepomp                            0
warmteterugwinning                    0
energieprestatie                      0
broeikaseffect                        0
energiezuinig                         0
zonnepaneel                           0

## Sum most frequent words with a negative sentiment per company

In [102]:
#Subset based on sentiment
NegENV = ENVcount[(ENVcount['Sentiment'] < 0)]

#Delete Sentiment column
del NegENV['Sentiment']

#Groupby search query
NegENV = NegENV.groupby('zoekopdracht').sum() #Get sum of words used

#Reset index
NegENV.reset_index(inplace = True)

#Rename column for merge
NegENV = NegENV.rename(columns={'zoekopdracht': 'Search Query'})

#Merge and create final dataset
finalNegENV = pd.merge(Companies2, NegENV, on = 'Search Query', how = 'inner')

#Delete unnecessary columns
del finalNegENV['Search Query']

#Non-numeric to index
#finalPosENV.set_index(['Organisation', 'Industry'], inplace=True)            

finalNegENV

#df.groupby(family)['Survived'].mean()

,Organisation,Industry,aardgasloos,biobrandstof,biodiversiteit,brandstof,brandstoffen,broeikaseffect,broeikasgas,circulair,...,warmteterugwinning,waterstof,windenergie,windmolen,windmolens,windpark,windparken,zonnepaneel,zonnepanelen,zonnepark
0,Aalberts N.V.,Industrie,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,ABN AMRO Group,Financiële dienstverleners,0,8,3,0,0,0,0,0,...,0,4,0,0,0,0,0,0,0,0
2,Accell Group,Consumenten goederen,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,Accsys Technologies,Chemie,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,Adyen,Technologie,0,0,0,0,0,0,0,1,...,0,0,0,0,0,0,0,0,0,0
5,AEGON,Financiële dienstverleners,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
6,Koninklijke Ahold / Ahold Delhaize,Detail- & groothandel,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
7,Air France-KLM,Transport & logistiek,0,0,0,5,1,0,1,0,...,0,4,0,0,0,0,0,0,0,0
8,AkzoNobel,Chemie,0,0,1,0,0,0,0,1,...,0,6,0,0,1,0,0,0,0,0
9,Alfen,Technologie,0,0,0,0,0,0,0,0,...,0,0,2,0,3,1,0,0,0,1
10,Altice Europe,Telecommunicatie,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
11,Coca-Cola European Partners,Voeding & drank,0,0,0,0,0,0,0,3,...,0,0,0,0,0,0,0,0,1,0
12,Royal Dutch Shell A,Olie & Gas,0,0,0,73,20,2,1,0,...,0,20,6,0,4,11,3,0,1,3
13,Greenchoice,Energie,0,0,0,0,0,0,0,2,...,0,3,10,6,5,7,0,1,125,5
14,Vattenfall,Energie,7,0,1,0,0,0,1,0,...,0,1,9,11,36,97,8,0,18,7
15,Vandebron,Energie,0,0,0,1,0,0,0,1,...,0,0,6,3,5,2,0,0,62,1
16,Eneco,Energie,0,0,0,0,1,0,0,0,...,0,1,1,0,0,0,0,0,0,0
17,Essent,Energie,0,0,1,5,0,0,0,0,...,0,5,3,0,1,0,0,0,65,0
18,ENGIE,Energie,7,0,0,0,0,0,0,20,...,0,1,2,2,6,1,0,0,25,6
19,NLE (Nederlande Energie Maatschappij),Energie,0,0,0,0,0,0,0,0,...,0,0,0,0,9,0,0,0,0,0
20,Oxxio,Energie,0,0,0,0,0,0,0,0,...,0,0,0,0,1,0,0,0,5,0
21,Alliander,Energie,0,0,0,0,0,0,0,0,...,0,21,1,0,6,2,0,0,25,0

## Select company and sort values

In [103]:
#Select specific company
NegENVShell = finalNegENV[(finalNegENV['Organisation'] == 'Royal Dutch Shell A')]

#Delete Industry column
del NegENVShell['Industry']
del NegENVShell['Organisation']

#Transpose (Switch rows and columns)
NegENVShell = NegENVShell.T.rename_axis('Words', axis=1)

#Rename column to company
NegENVShell.rename(columns={ NegENVShell.columns[0]: "Royal Dutch Shell A" }, inplace = True)

#Sort values
NegENVShell.sort_values(by = 'Royal Dutch Shell A', ascending = False, inplace = True)

NegENVShell

Words               Royal Dutch Shell A
olievervuiling                      136
olie                                122
fossiele                            116
brandstof                            73
klimaatverandering                   63
klimaatzaak                          62
duurzaamheid                         47
uitstoot                             38
klimaat                              36
fossiel                              29
brandstoffen                         20
waterstof                            20
duurzame                             19
milieu                               17
duurzaam                             14
klimaatakkoord                       12
transitie                            12
windpark                             11
energietransitie                     10
windenergie                           6
klimaatdoelen                         6
klimaatneutraal                       6
hernieuwbare                          6
verduurzaming                         5
windmolens                            4
zonnepark                             3
hernieuwbaar                          3
geothermie                            3
windparken                            3
verduurzamen                          2
broeikaseffect                        2
kolencentrale                         2
zonnepanelen                          1
klimaatdoel                           1
greenhouse                            1
broeikasgas                           1
ecologisch                            1
ecosysteem                            1
klimaatverdrag                        0
warmtepomp                            0
biodiversiteit                        0
zonnepaneel                           0
circulair                             0
circulaire                            0
windmolen                             0
warmteterugwinning                    0
energieakkoord                        0
koolstofdioxide                       0
energieneutraal                       0
energieprestatie                      0
energiezuinig                         0
solar                                 0
renewables                            0
recyclen                              0
kernenergie                           0
biobrandstof                          0
aardgasloos                           0

In [64]:
last_row_name = PosENVShell.index[-1]
PosENVShell2 = PosENVShell.T.sort_values(columns=last_row_name).T

TypeError: sort_values() got an unexpected keyword argument 'columns'

In [62]:
PosENVShell2 = PosENVShell.reindex(columns=['max', cols])
PosENVShell2

TypeError: unhashable type: 'list'

In [58]:
cols = list(PosENVShell.columns.values)
cols

['Organisation',
 'aardgasloos',
 'biobrandstof',
 'biodiversiteit',
 'brandstof',
 'brandstoffen',
 'broeikaseffect',
 'broeikasgas',
 'circulair',
 'circulaire',
 'duurzaam',
 'duurzaamheid',
 'duurzame',
 'ecologisch',
 'ecosysteem',
 'energieakkoord',
 'energieneutraal',
 'energieprestatie',
 'energietransitie',
 'energiezuinig',
 'fossiel',
 'fossiele',
 'geothermie',
 'greenhouse',
 'hernieuwbaar',
 'hernieuwbare',
 'kernenergie',
 'klimaat',
 'klimaatakkoord',
 'klimaatdoel',
 'klimaatdoelen',
 'klimaatneutraal',
 'klimaatverandering',
 'klimaatverdrag',
 'klimaatzaak',
 'kolencentrale',
 'koolstofdioxide',
 'milieu',
 'olie',
 'olievervuiling',
 'recyclen',
 'renewables',
 'solar',
 'transitie',
 'uitstoot',
 'verduurzamen',
 'verduurzaming',
 'warmtepomp',
 'warmteterugwinning',
 'waterstof',
 'windenergie',
 'windmolen',
 'windmolens',
 'windpark',
 'windparken',
 'zonnepaneel',
 'zonnepanelen',
 'zonnepark']

In [265]:
count_vect_df['circulaire'].sum()

318

In [7]:
count_vect_df.drop([col for col, val in count_vect_df.sum().iteritems() if val < 15], axis=1, inplace=True) #Returns 10717 unique words
count_vect_df

,aalb,aalberts,aanbieden,aanbieder,aanbieding,aanbod,aandacht,aandeel,aandeelhouder,aandeelhouders,...,zwanen,zware,zwart,zwarte,zweden,zweedse,zwerfafval,zwitserse,zwolle,zzp
0,1,2,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,1,2,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,1,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,1,1,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,1,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
64995,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
64996,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
64997,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
64998,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
64999,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [ ]:
count_vect_df.drop([col for col, val in count_vect_df.sum().iteritems() if val < 50], axis=1, inplace=True) #Returns 10717 unique words
count_vect_df

In [17]:
count_vect_df.drop([col for col, val in count_vect_df.sum().iteritems() if val < 90], axis=1, inplace=True) #Returns 10717 unique words
count_vect_df

,aanbieden,aanbieding,aanbod,aandacht,aandeel,aandeelhouder,aandeelhouders,aandelen,aankoop,aanmelden,...,zorg,zorgen,zorgt,zouden,zoveel,zowel,zuid,zullen,zwolle,zzp
0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
64995,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
64996,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
64997,0,0,0,0,0,0,0,0,0,0,...,0,0,1,0,0,0,0,0,0,0
64998,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
64999,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [29]:
count_vect_df.drop([col for col, val in count_vect_df.sum().iteritems() if val < 150], axis=1, inplace=True) #Returns 10717 unique words
count_vect_df

,aalberts,aandacht,aandeel,aandeelhouder,aandeelhouders,aandelen,aankoop,aansprakelijk,aantal,abm,...,zoek,zoekt,zojuist,zolang,zorg,zorgen,zouden,zoveel,zuid,zullen
0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,2,0,0,0,0,0,1,0,0,0,...,0,0,0,1,0,0,0,0,0,0
2,2,0,0,0,0,0,1,0,0,0,...,0,0,0,1,0,0,0,0,0,0
3,2,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,0,0,0,0,0,0,0,0,0,0,...,0,0,1,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
81582,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
81583,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
81584,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
81585,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
81586,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [27]:
count_vect_df.drop([col for col, val in count_vect_df.sum().iteritems() if val < 200], axis=1, inplace=True) #Returns 10717 unique words
count_vect_df

,aandeel,aandelen,abn,accell,actie,adyen,aegon,aex,af,afgelopen,...,zaandam,zegt,zet,zie,zien,zit,zoals,zoek,zoekt,zonnepanelen
0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
1,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
39995,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
39996,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
39997,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
39998,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
39999,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [31]:
count_vect_df.columns

Index(['aalberts', 'aandeel', 'aandeelhouders', 'aandelen', 'aansprakelijk',
       'aantal', 'abm', 'abn', 'abnamro', 'about',
       ...
       'zit', 'zitten', 'zoals', 'zoek', 'zoekt', 'zojuist', 'zolang',
       'zorgen', 'zuid', 'zullen'],
      dtype='object', length=773)

In [24]:
wordlist = list(count_vect_df.columns.values)
taillist = list(count_vect_df.columns.values)[-1036:]
taillist

['duurzame',
 'ebay',
 'echt',
 'echte',
 'echter',
 'economie',
 'eelde',
 'eerder',
 'eerst',
 'eerste',
 'eigen',
 'eigenaar',
 'eigenlijk',
 'eind',
 'einde',
 'eindelijk',
 'eindtijd',
 'el',
 'elbers',
 'elektra',
 'elektriciteit',
 'elektriciteitsnet',
 'elektrisch',
 'elektrische',
 'elektrotechniek',
 'elk',
 'elkaar',
 'elke',
 'email',
 'emerce',
 'eneco',
 'energeia',
 'energie',
 'energiebedrijf',
 'energiebedrijven',
 'energiecheck',
 'energieleverancier',
 'energieleveranciers',
 'energiemaatschappij',
 'energiemarkt',
 'energiemeter',
 'energierekening',
 'energiesector',
 'energietransitie',
 'energy',
 'engie',
 'engineer',
 'engineering',
 'enige',
 'enkele',
 'erg',
 'ergens',
 'erop',
 'ers',
 'eruit',
 'ervaren',
 'ervaring',
 'ervoor',
 'essent',
 'etc',
 'eu',
 'eur',
 'euro',
 'europa',
 'europe',
 'europese',
 'ev',
 'even',
 'event',
 'ex',
 'excuses',
 'experts',
 'extra',
 'fabriek',
 'facebook',
 'fail',
 'fd',
 'februari',
 'feit',
 'fijn',
 'finance',
 'financi',
 'financial',
 'financieel',
 'flevoland',
 'flink',
 'flinke',
 'fn',
 'fnv',
 'for',
 'fors',
 'fossiele',
 'foto',
 'fout',
 'france',
 'frankrijk',
 'frans',
 'franse',
 'friesland',
 'fugro',
 'fulltime',
 'functie',
 'functieomschrijving',
 'ga',
 'gaan',
 'gaat',
 'galapagos',
 'gas',
 'gebeld',
 'gebeurt',
 'gebied',
 'gebouw',
 'gebruik',
 'gebruiken',
 'gebruikt',
 'gedaan',
 'geef',
 'geeft',
 'gefeliciteerd',
 'gegaan',
 'gegevens',
 'gehad',
 'gek',
 'gekregen',
 'geld',
 'gelderland',
 'geleden',
 'gelezen',
 'gelijk',
 'geloof',
 'gelukkig',
 'gemaakt',
 'gemeente',
 'gemeld',
 'genoeg',
 'genomen',
 'geplaatst',
 'gerrit',
 'gesloten',
 'gesprek',
 'gestart',
 'gestuurd',
 'getroffen',
 'geval',
 'geven',
 'gewoon',
 'geworden',
 'gezet',
 'gezien',
 'gezocht',
 'ging',
 'gisteren',
 'goed',
 'goede',
 'goedemorgen',
 'goedkoper',
 'goeie',
 'google',
 'gouden',
 'graag',
 'gratis',
 'green',
 'greenchoice',
 'groei',
 'groeien',
 'groen',
 'groene',
 'groep',
 'groningen',
 'groot',
 'grootste',
 'grote',
 'group',
 'haag',
 'haalt',
 'haarlem',
 'hadden',
 'hague',
 'halen',
 'half',
 'hallo',
 'hand',
 'handelen',
 'handen',
 'hard',
 'hebt',
 'heel',
 'heijn',
 'heineken',
 'helaas',
 'hele',
 'helemaal',
 'helft',
 'help',
 'helpen',
 'helpt',
 'hema',
 'hemweg',
 'hen',
 'hengelo',
 'herstel',
 'hetzelfde',
 'hi',
 'hoekstra',
 'hoeveel',
 'hoge',
 'hoger',
 'hogere',
 'hoi',
 'holland',
 'hollandse',
 'homekit',
 'honderden',
 'hoofd',
 'hoofdkantoor',
 'hoog',
 'hoogte',
 'hoop',
 'hoor',
 'horeca',
 'horen',
 'houden',
 'houdt',
 'hr',
 'huidige',
 'huis',
 'huishoudens',
 'hypotheken',
 'ict',
 'idee',
 'iedere',
 'iedereen',
 'iex',
 'impact',
 'inci',
 'index',
 'industrie',
 'ineens',
 'info',
 'informatie',
 'ing',
 'initiatief',
 'inloggen',
 'inmiddels',
 'innovatie',
 'innovatieve',
 'installaties',
 'interessant',
 'interesse',
 'internet',
 'interview',
 'investeert',
 'investeren',
 'inzet',
 'inzetten',
 'inzicht',
 'ipad',
 'ipay',
 'iphone',
 'ipv',
 'it',
 'ivm',
 'jaar',
 'jaarafrekening',
 'jaarnota',
 'jammer',
 'jan',
 'januari',
 'jaren',
 'jarig',
 'jij',
 'jo',
 'jobsinenergy',
 'jogg',
 'johan',
 'jones',
 'jongeren',
 'jou',
 'jouw',
 'jouwbaan',
 'juist',
 'juli',
 'jullie',
 'jumbo',
 'juni',
 'junior',
 'kabinet',
 'kamer',
 'kans',
 'kansen',
 'kant',
 'kantoor',
 'keer',
 'kennis',
 'kenter',
 'keuze',
 'keuzes',
 'kies',
 'kiest',
 'kiezen',
 'kijk',
 'kijken',
 'kinderen',
 'klaar',
 'klacht',
 'klachten',
 'klant',
 'klantadviseur',
 'klanten',
 'klantenservice',
 'klein',
 'kleine',
 'klimaat',
 'klimaatakkoord',
 'klimaatverandering',
 'klimaatzaak',
 'klm',
 'klopt',
 'km',
 'koers',
 'koersdoel',
 'kolencentrale',
 'kom',
 'komen',
 'komende',
 'komt',
 'koop',
 'koopt',
 'kop',
 'kopen',
 'koploper',
 'kort',
 'korte',
 'korting',
 'kost',
 'kosten',
 'kpn',
 'kreeg',
 'krijg',
 'krijgen',
 'krijgt',
 'kun',
 'kunt',
 'kust',
 'kwam',
 'kwartaal',
 'kwh',
 'kwijt',
 'laadpalen',
 'laag',
 'laat',
 'laatste',
 'lage',
 'lager',
 'lagere',
 'lanceert',
 'land',
 'lang',
 'lange',
 'langer',
 'langs',
 'last',
 'lastig',
 'laten',
 'later',
 'le',
 'leden',
 'lees',
 'leest',
 'leeuwarden',
 'leggen',
 'legt',
 'leiden',
 'lekker',
 'lelystad',
 'let',
 'leuk',
 'leuke',
 'leven',
 'leverancier',
 'leveren',
 'levert',
 'lezen',
 'liander',
 'licht',
 'lid',
 'liever',
 'liggen',
 'ligt',
 'lijkt',
 'lijn',
 'link',
 'live',
 'liveblog',
 'locatie',
 'lockdown',
 'logo',
 'lokale',
 'londen',
 'loopt',
 'lopen',
 'lucht',
 'luchtvaart',
 'luister',
 'lukt',
 'maak',
 'maakt',
 'maakte',
 'maand',
 'maandag',
 'maandbedrag',
 'maanden',
 'maart',
 'maatschappij',
 'mabel',
 'mag',
 'magazine',
 'mail',
 'maken',
 'man',
 'management',
 'manager',
 'manier',
 'manieren',
 'marketeer',
 'marketing',
 'markt',
 'marktplaats',
 'mede',
 'medewerker',
 'medewerkers',
 'media',
 'medior',
 'mee',
 'meerdere',
 'meest',
 'mei',
 'meld',
 'melding',
 'meldt',
 'mensen',
 'meppel',
 'merk',
 'merken',
 'meteen',
 'meter',
 'meterstanden',
 'milieu',
 'milieudefensie',
 'miljard',
 'miljarden',
 'miljoen',
 'miljoenen',
 'miljoenenbonus',
 'min',
 'minder',
 'minister',
 'minuten',
 'minuut',
 'mis',
 'misschien',
 'mkb',
 'mln',
 'mn',
 'model',
 'moeder',
 'moederbedrijf',
 'moeilijk',
 'moeten',
 'mogelijk',
 'mogen',
 'moment',
 'momenteel',
 'monteur',
 'monteurs',
 'mooi',
 'mooie',
 'morgen',
 'muller',
 'multinationals',
 'naam',
 'naast',
 'nadat',
 'namelijk',
 'namens',
 'nationaal',
 'natuurlijk',
 'nederland',
 'nederlanders',
 'nederlands',
 'nederlandse',
 'nee',
 'neem',
 'neemt',
 'negatieve',
 'nemen',
 'net',
 'netbeheerder',
 'netwerk',
 'new',
 'nico',
 'niemand',
 'nieuw',
 'nieuwe',
 'nieuws',
 'nieuwsblik',
 'nieuwsbureau',
 'nieuwste',
 'nigeria',
 'nigeriaanse',
 'nijmegen',
 'niks',
 'nl',
 'nle',
 'nn',
 'nodig',
 'nooit',
 'noord',
 'normaal',
 'nos',
 'nou',
 'november',
 'nummer',
 'nuon',
 'nv',
 'oa',
 'officer',
 'oh',
 'oktober',
 'olie',
 'olievervuiling',
 'omgeving',
 'omhoog',
 'oms',
 'omzet',
 'omzetgroei',
 'on',
 'ondanks',
 'onderdeel',
 'onderhoud',
 'ondernemen',
 'ondernemer',
 'ondernemers',
 'onderstaande',
 'onderuit',
 'onderweg',
 'onderzoek',
 'onderzoekt',
 'ongemak',
 'ongeveer',
 'online',
 'ontvang',
 'ontvangen',
 'ontwikkeling',
 'onze',
 'ooit',
 'oorzaak',
 'opdracht',
 'open',
 'openen',
 'opening',
 'opent',
 'opgelost',
 'oplossen',
 'oplossing',
 'oplossingen',
 'opnieuw',
 'oprichter',
 'opties',
 'oranje',
 'organisatie',
 'oud',
 'oude',
 'ov',
 'overgenomen',
 'overgestapt',
 'overheid',
 'overname',
 'overstap',
 'overstappen',
 'overzicht',
 'oxxio',
 'paar',
 'pakken',
 'parijs',
 'partijen',
 'partner',
 'partners',
 'parttime',
 'pas',
 'passagiers',
 'pensioen',
 'per',
 'persbericht',
 'personeel',
 'philips',
 'pieter',
 'plaats',
 'plaatsen',
 'plan',
 'plannen',
 'plastic',
 'platform',
 'plek',
 'plus',
 'podcast',
 'politiek',
 'politieke',
 'positief',
 'positieve',
 'post',
 'postcode',
 'postcodes',
 'postnl',
 'powerdeal',
 'prachtige',
 'praten',
 'precies',
 'preferenso',
 'preventieakkoord',
 'prijs',
 'prijzen',
 'prima',
 'probeer',
 'proberen',
 'probleem',
 'problemen',
 'procent',
 'product',
 'producten',
 'productie',
 'profiteren',
 'programma',
 'project',
 'projecten',
 'projectleider',
 'prosus',
 'protection',
 'provincie',
 'qirion',
 'qurrent',
 'raad',
 'rabobank',
 'race',
 'randstad',
 'rdinator',
 're',
 'reactie',
 'realiseren',
 'rechter',
 'rechtszaak',
 'reclame',
 'reclames',
 'reden',
 'regering',
 'regio',
 'rekening',
 'rente',
 'resultaat',
 'resultaten',
 'retail',
 'retweet',
 'richting',
 'rij',
 'rijden',
 'risico',
 'risk',
 'rode',
 'rol',
 'rond',
 'rondje',
 'rood',
 'rotterdam',
 'rotterdamse',
 'royal',
 'rt',
 'ruim',
 'ruimte',
 'rutte',
 'rwe',
 'sales',
 'samen',
 'samenwerken',
 'samenwerking',
 'sassenheim',
 'schade',
 'schikt',
 'schiphol',
 'schrapt',
 'sector',
 'senior',
 'september',
 'service',
 'services',
 'shell',
 'shop',
 'short',
 'sinds',
 'site',
 'situatie',
 'slag',
 'slecht',
 'slechts',
 'slim',
 'slimme',
 'slot',
 'slotcall',
 'sluit',
 'sluiten',
 'snel',
 'sneltest',
 'social',
 'sociale',
 'solar',
 'solliciteer',
 'soort',
 'spaar',
 'specialist',
 'specialty',
 'speelt',
 'sponsor',
 'staan',
 'staat',
 'staatssteun',
 'stad',
 'staking',
 'stakingen',
 'stand',
 'stap',
 'stappen',
 'stapt',
 'start',
 'starten',
 'steeds',
 'stellen',
 'stelt',
 'sterk',
 'sterke',
 'steun',
 'stijgen',
 'stijgt',
 'stond',
 'stop',
 'stoppen',
 'stopt',
 'storing',
 'straat',
 'straks',
 'strategie',
 'strijd',
 'stroom',
 'stroomstoring',
 'stuk',
 'sturen',
 'subsidie',
 'succes',
 'super',
 'supermarkt',
 'supermarktconcern',
 'supermarkten',
 'systeem',
 'systemengineering',
 'takeaway',
 'talent',
 'tarief',
 'tarieven',
 'team',
 'tech',
 'techniek',
 'technisch',
 'technische',
 'telecomengineer',
 'telecommunicatie',
 'telefonisch',
 'telefoon',
 'ten',
 'tennet',
 'tennis',
 'ter',
 'terecht',
 'termijn',
 'termijnbedrag',
 'terug',
 'terwijl',
 'tesla',
 'test',
 'testcoureur',
 'testen',
 'the',
 'thermostaat',
 'thuis',
 'tijd',
 'tijdelijk',
 'tijdens',
 'tip',
 'tips',
 'to',
 'toe',
 'toekomst',
 'toernooi',
 'top',
 'topman',
 'totaal',
 'trade',
 'traders',
 'traineeship',
 'transitie',
 'trekt',
 'trend',
 'trots',
 'trui',
 'tussen',
 'tv',
 'twee',
 'tweede',
 'twitter',
 'uitdaging',
 'uitspraak',
 'uitstoot',
 'unibail',
 'unilever',
 'up',
 'update',
 'usa',
 'utrecht',
 'uur',
 'vaak',
 'vacature',
 'vacatures',
 'vallen',
 'valt',
 'vanaf',
 'vanavond',
 'vandaag',
 'vandebron',
 'vanmiddag',
 'vanuit',
 'vanwege',
 'vast',
 'vaste',
 'vastgoed',
 'vattenfall',
 'vd',
 'veilig',
 'vele',
 'veluwe',
 'ver',
 'verantwoordelijk',
 'verbruik',
 'verder',
 'verdien',
 'verdienen',
 'verduurzamen',
 'verduurzaming',
 'verf',
 'vergeten',
 'verhaal',
 'verhoogt',
 'verkocht',
 'verkoop',
 'verkoopt',
 'verkopen',
 'verkoper',
 'verkopers',
 'verlaagt',
 'verlies',
 'verliezen',
 'verschil',
 'verschillende',
 'vertellen',
 'vertelt',
 'vertrouwen',
 'vervangen',
 'vervolgens',
 'verwacht',
 'verwachte',
 'verwachten',
 'verwachting',
 'via',
 'video',
 'vier',
 'vijf',
 'vind',
 'vinden',
 'vindt',
 'vliegen',
 'vliegt',
 'vliegtuigen',
 'vlucht',
 'vluchten',
 'voert',
 'voicemail',
 'vol',
 'volgen',
 'volgend',
 'volgende',
 'volgens',
 'volgt',
 'volledig',
 'vooral',
 'voorbeeld',
 'voorbij',
 'voorlopig',
 'voormalig',
 'vooruit',
 'voorzien',
 'voorzitter',
 'vorig',
 'vorige',
 'vraag',
 'vraagt',
 'vragen',
 'vrienden',
 'vriendenlink',
 'vrij',
 'vrijdag',
 'vrije',
 'vroeger',
 'vs',
 'vvd',
 'vws',
 'waar',
 'waarbij',
 'waard',
 'waarde',
 'waarin',
 'waarom',
 'waaronder',
 'wacht',
 'wachten',
 'wanneer',
 'warme',
 'warmetruiendag',
 'warmte',
 'water',
 'waterstof',
 'we',
 'webcare',
 'website',
 'wederom',
 'wedstrijd',
 'week',
 'weekend',
 'weer',
 'weerstand',
 'weet',
 'weg',
 'wegens',
 'weinig',
 'weken',
 'wel',
 'welke',
 'welkom',
 'wereld',
 'wereldwijd',
 'werk',
 'werken',
 'werknemers',
 'werkt',
 'werkvoorbereider',
 'werkzaamheden',
 'west',
 'weten',
 'wij',
 'wilde',
 'willen',
 'wilt',
 'win',
 'wind',
 'windenergie',
 'windmolens',
 'windpark',
 'winkels',
 'winnaar',
 'winnaars',
 'winnen',
 'winst',
 'wint',
 'wist',
 'witwassen',
 'woensdag',
 'woning',
 'woningen',
 'word',
 'world',
 'youngcapital',
 'zaak',
 'zaandam',
 'zag',
 'zakelijk',
 'zakelijke',
 'zaken',
 'zalm',
 'zaterdag',
 'zee',
 'zeer',
 'zeg',
 'zeggen',
 'zegt',
 'zei',
 ...]

In [45]:
for column in count_vect_df:
    if column.sum() < 10:
        del column
        
count_vect_df

AttributeError: 'str' object has no attribute 'sum'

In [125]:
from sklearn.feature_extraction.text import CountVectorizer


vectorizer = CountVectorizer(lowercase = False)

X_train_counts = vectorizer.fit_transform(Data2['Stemmed Clean'])
X_train_counts.shape 


#vectorizer = CountVectorizer()

#vectorizer.fit(Data2['Stemmed Clean'])

#countVectorizer = CountVectorizer(analyzer=clean_text) 

#countVectorizer

#countVector = countVectorizer.fit_transform(Data['Text Clean'])
#print('{} Number of tweets has {} words'.format(countVector.shape[0], countVector.shape[1]))
#print(countVectorizer.get_feature_names())

TypeError: expected string or bytes-like object

In [10]:
'''
def detect(x):
    try:
        lang = detect(x)
    except:
        lang = 'Other'
        print('Current row could not be detected:' )    
        return lang

Data['Lang'] = Data['bericht tekst'].apply(detect)

SyntaxError: EOF while scanning triple-quoted string literal (<ipython-input-10-242e6c36a157>, line 10)

In [16]:
#print(min(Data2['Number of Chars']))

In [17]:
#print(len(Data['bericht tekst']))

In [18]:
'''
def detect(x):
    for row in x['bericht tekst']:
        try:
            x['language'] = detect(row[0])
        except:
            x['language'] = 'error'
            print("This row throws and error:", row[0]) 
            
    return x

Data['Lang'] = Data['bericht tekst'].apply(detect)

SyntaxError: EOF while scanning triple-quoted string literal (<ipython-input-18-a9e515c1a971>, line 12)

In [19]:
'''
for row in Data['bericht tekst']:
    try:
        Data['language'] = detect(row[0])
    except:
        language = "error"
        print("This row throws and error:", row[0])
    row.append(language)
    all.append(row)
'''

'\nfor row in Data[\'bericht tekst\']:\n    try:\n        Data[\'language\'] = detect(row[0])\n    except:\n        language = "error"\n        print("This row throws and error:", row[0])\n    row.append(language)\n    all.append(row)\n'

In [20]:
'''
Data2 = Data.head(100)

start_time = time.time()

for row in Data2['bericht tekst']:
    try: 
        Data2['language'] = Data2['bericht tekst'].apply(detect)
    except:
        Data2['language'] = "error"
        print("This row throws and error:", row[0])

        
print("--- %s seconds ---" % (time.time() - start_time))


Data2
'''

'\nData2 = Data.head(100)\n\nstart_time = time.time()\n\nfor row in Data2[\'bericht tekst\']:\n    try: \n        Data2[\'language\'] = Data2[\'bericht tekst\'].apply(detect)\n    except:\n        Data2[\'language\'] = "error"\n        print("This row throws and error:", row[0])\n\n        \nprint("--- %s seconds ---" % (time.time() - start_time))\n\n\nData2\n'

In [32]:
string.punctuation

'!"#$%&\'()*+,-./:;<=>?@[\\]^_`{|}~'

In [21]:
import string

In [11]:
Data2 = Data.head(1500)
start_time = time.time()
Data2['language'] = Data2['bericht tekst'].apply(detect)
print("--- %s seconds ---" % (time.time() - start_time))
Data2

--- 16.145412921905518 seconds ---

/Users/Marcel/opt/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  This is separate from the ipykernel package so we can avoid doing imports until

,zoekopdracht,datum,bericht tekst,type bron,language
0,"""Aalberts N.V."" OR ""AALB"" (src:t...",2021-04-12 18:18,Aero Logic | D-[AALB] | Boeing 777-FZN | Clitheroe 12/04/2021 #aerologic #daalb #boeing #boeing777 #boeing777f #cargo #avgeek #aviation #planes #planespotting #planespotter #aviationphotography #airplan #aircraft #planespotter #fly #photography #spotting #highflyers #ott https://t.co/4uYPiwTjAw,twitter,en
1,"""Aalberts N.V."" OR ""AALB"" (src:t...",2021-03-18 11:53,$[AALB] #AALBERTS @aalbertsindustr - Dagelijks: AALBERTS NV maakt een erg sterke bullish trend door. Traders kunnen overwegen alleen longposities te handelen (op moment van aankoop) zolang de koers... https://t.co/hOiR5KPSeX,twitter,nl
2,"""Aalberts N.V."" OR ""AALB"" (src:t...",2021-03-18 11:53,$[AALB] #AALBERTS - Dagelijks: AALBERTS NV maakt een erg sterke bullish trend door. Traders kunnen overwegen alleen longposities te handelen (op moment van aankoop) zolang de koers... https://t.co/dZWInNPIYj,twitter,nl
3,"""Aalberts N.V."" OR ""AALB"" (src:t...",2021-02-16 12:41,Nederlandse scale-up Nearfield vult het metrologie-gat in de mondiale chipindustrie #3Dstructuren Aalberts advanced mechatronics [Aalberts N.V]. #advancedmotioncontrol #AMAT Applied Materials ASML #BenjaminBunday #chipindustrie #d…https://t.co/dTyXJs2KcP https://t.co/3R88TCMjts,twitter,en
4,"""Aalberts N.V."" OR ""AALB"" (src:t...",2020-11-05 14:53,"Zojuist de [AALB] dec20 30 call (optietip 176) verkocht voor €3,25. Gekocht voor €1,10. Had achteraf gezien beter gekund, maar je kunt toch niet echt ontevreden zijn met 195% winst. https://t.co/OsAvGABjst",twitter,nl
...,...,...,...,...,...
1381,"""ABN AMRO Group"" OR ""ABN"" OR ""AB...",2021-04-14 20:33,"🇿🇦🇾🇪 De Zuid-Afrikaan #NeoMatloga heeft de tiende [ABN] Amro Kunstprijs gewonnen. Matloga kreeg de prijs uit handen van Hermitagedirecteur Annabelle Birnie en Danila Cohen, curator van de [ABN] Amro kunstcollectie, in de verder verlaten Hermitage. https://t.co/7sDCLYpTgB",twitter,nl
1382,"""ABN AMRO Group"" OR ""ABN"" OR ""AB...",2021-04-14 20:20,Kunstenaar Neo Matloga is de winnaar van de 10e editie van de [ABN AMRO] Kunstprijs! Met deze prijs steunen we kunstenaars bij hun ontwikkeling en geven we hen een podium om een zo groot mogelijk publiek te bereiken. https://t.co/RBadVHPy08,twitter,nl
1383,"""ABN AMRO Group"" OR ""ABN"" OR ""AB...",2021-04-14 20:12,"Slotcall: Muziek in pijplijn Galapagos: AEX +0,6% en een rondje langs TomTom, Fagron, Galapagos, ASML, ASMI, [ABN] Amro, ArcelorMittal, Alfen, Royal Dutch Shell en meer! https://t.co/bYDwekPh9S",twitter,nl
1384,"""ABN AMRO Group"" OR ""ABN"" OR ""AB...",2021-04-14 19:16,0-9 RX-1 [[[ABN] Op-2]] (13:16:15),twitter,ro
1385,"""ABN AMRO Group"" OR ""ABN"" OR ""AB...",2021-04-14 19:16,0-9 B-1 [[[ABN] Op-2]] (13:16:1),twitter,tl

In [ ]:
Data2['language'] = Data2['bericht tekst'].apply(detect)
Data2

In [102]:
from sklearn.feature_extraction.text import CountVectorizer

vectorizer = CountVectorizer()

vectorizer.fit(Data2[''])

#countVectorizer = CountVectorizer(analyzer=clean_text) 

#countVectorizer

#countVector = countVectorizer.fit_transform(Data['Text Clean'])
#print('{} Number of tweets has {} words'.format(countVector.shape[0], countVector.shape[1]))
#print(countVectorizer.get_feature_names())

'sant'

In [87]:
from nltk.stem import WordNetLemmatizer

lemmatizer = WordNetLemmatizer()
print(lemmatizer.lemmatize('katten'))

katten

In [28]:
from sklearn.feature_extraction.text import CountVectorizer

countVectorizer = CountVectorizer(analyzer=clean_text) 

countVectorizer

#countVector = countVectorizer.fit_transform(Data['Text Clean'])
#print('{} Number of tweets has {} words'.format(countVector.shape[0], countVector.shape[1]))
#print(countVectorizer.get_feature_names())

CountVectorizer(analyzer=<function clean_text at 0x7f90b563acb0>, binary=False,
                decode_error='strict', dtype=<class 'numpy.int64'>,
                encoding='utf-8', input='content', lowercase=True, max_df=1.0,
                max_features=None, min_df=1, ngram_range=(1, 1),
                preprocessor=None, stop_words=None, strip_accents=None,
                token_pattern='(?u)\\b\\w\\w+\\b', tokenizer=None,
                vocabulary=None)

In [21]:
countVector = countVectorizer.fit_transform(Data['Text Clean'])
countVector

ValueError: The truth value of a Series is ambiguous. Use a.empty, a.bool(), a.item(), a.any() or a.all().

In [23]:
vectorizer = countVectorizer()
vectorizer.fit(Data['Text Clean'])

TypeError: 'CountVectorizer' object is not callable

In [12]:
#Tokenizing - Word tokenizers & Sentence tokenizers
#Lexicon and Corpora
#Corpora - Body of text: Language etc, journals, speeches
#Lexicon - Dictionary: Words and their meaning
    #investor speak 'bull'= positive about the market. English 'bull '
    #English language 'bull'= the animal

In [19]:
'''
Sustainability word list
Environmental
Energy efficiency, material efficiency, water consumption, resources, pollution, three waste, emissions, air emissions, water runoff, solid waste, environmental protection, environmental investment, environmental expenditures, material use, energy use, environment prevention, air pollution, water pollution, solid waste, land use, gas emission, non-renewable material used, renewable material used, fuel consumption, water recycled / reused, GHG emission, biodiversity, atmosphere, land, oceans, seas, coast, fresh water, spills, hazardous waste, global warming, nuisance, product toxicity
Social
Interaction with workers, interaction with customers, interaction with community, social impact, product liability, worker well-being, worker status, employment stability, human rights, health and safety, job satisfaction, education, training, customer satisfaction, contribution to local community, profit, taxes, safety, justice, diversity, labour, social inclusion, indigenous people, employee turnover, strikes, lockouts, injury, disease, absenteeism, fatalities, discrimination, corruption, non-monetary sanctions, Product Stewardship Programme, equity, housing, security, population, job opportunity, employment compensation, career development, mobility infrastructure, social pathologies, social cohesion, fatalities, local communities, bribery, business ethic
Economic
Size of the company, capacity for growth, total assets, total production value, total sales, total profit, total asset turnover, current asset turnover, profitability, ratio of profit to costs, return on equity, ability to raise cash, net working capital, debt repayment capability, debt-to-assets ratio, technical innovation capability, research and development spending, market control capability, export share of total sales, fiscal stewardship, research & development, internal controls, investment, independent directors, female directors, competences, stakeholder representation, consumption, financial benefits, exploration cost, safety fines, wealth creation, distribution wealth, pollution prevention
'''

'\nSustainability word list\nEnvironmental\nEnergy efficiency, material efficiency, water consumption, resources, pollution, three waste, emissions, air emissions, water runoff, solid waste, environmental protection, environmental investment, environmental expenditures, material use, energy use, environment prevention, air pollution, water pollution, solid waste, land use, gas emission, non-renewable material used, renewable material used, fuel consumption, water recycled / reused, GHG emission, biodiversity, atmosphere, land, oceans, seas, coast, fresh water, spills, hazardous waste, global warming, nuisance, product toxicity\nSocial\nInteraction with workers, interaction with customers, interaction with community, social impact, product liability, worker well-being, worker status, employment stability, human rights, health and safety, job satisfaction, education, training, customer satisfaction, contribution to local community, profit, taxes, safety, justice, diversity, labour, social inclusion, indigenous people, employee turnover, strikes, lockouts, injury, disease, absenteeism, fatalities, discrimination, corruption, non-monetary sanctions, Product Stewardship Programme, equity, housing, security, population, job opportunity, employment compensation, career development, mobility infrastructure, social pathologies, social cohesion, fatalities, local communities, bribery, business ethic\nEconomic\nSize of the company, capacity for growth, total assets, total production value, total sales, total profit, total asset turnover, current asset turnover, profitability, ratio of profit to costs, return on equity, ability to raise cash, net working capital, debt repayment capability, debt-to-assets ratio, technical innovation capability, research and development spending, market control capability, export share of total sales, fiscal stewardship, research & development, internal controls, investment, independent directors, female directors, competences, stakeholder representation, consumption, financial benefits, exploration cost, safety fines, wealth creation, distribution wealth, pollution prevention\n'